"""First-time visitor operating knowledge for India.

These are short, searchable claims for travelers who do not yet know how India
works. Fast-changing facts stay linked to official pages and are marked for
refresh; practical advice is deliberately marked estimated rather than presented
as law or medical advice.
"""

SOURCES = {
    "visa": ("Bureau of Immigration — India Visa Online", "https://indianvisaonline.gov.in/", "official", "primary"),
    "customs": ("CBIC — International Travellers", "https://www.cbic.gov.in/entities/internationalTravellers", "official", "primary"),
    "tourist_help": ("Ministry of Tourism — Tourist Helpline", "https://tourism.gov.in/sites/default/files/2024-07/PIB2038517.pdf", "official", "primary"),
    "emergency": ("Government of India — ERSS 112", "https://112.gov.in/about", "official", "primary"),
    "rail": ("IRCTC — Foreign Tourist Quota Booking", "https://contents.irctc.co.in/en/ForeignTouristQuotaBooking.pdf", "official", "primary"),
    "incredible_faq": ("Incredible India — Traveller FAQs", "https://www.incredibleindia.gov.in/en/faqs", "official", "primary"),
    "incredible_culture": ("Incredible India — People and Culture", "https://www.incredibleindia.gov.in/en/people-and-culture", "official", "primary"),
    "sustainable": ("Incredible India — Travel for LiFE", "https://www.incredibleindia.gov.in/en/travel-for-life", "official", "primary"),
    "health": ("CDC — India Traveler View", "https://wwwnc.cdc.gov/travel/destinations/traveler/none/India", "official", "primary"),
    "telecom": ("Department of Telecommunications — Visitor SIM KYC", "https://www.dot.gov.in/static/uploads/2026/02/7584a7bd36234512e26ece5d2c7b5017.pdf", "official", "primary"),
    "weather": ("India Meteorological Department", "https://mausam.imd.gov.in/", "official", "primary"),
}


def _profile(category: str, stage: str = "before_and_during_trip", priority: str = "high", **extra: str) -> dict:
    return {
        "knowledgeCategory": category,
        "travelerStage": stage,
        "priority": priority,
        **extra,
    }


# (name, city, aliases, source_key, entity_type, claim, confidence, profile)
ENTRIES = [
    ("India visa starting point", "India", ["India visa", "visa for India", "do I need a visa"], "visa", "visa_info",
     "Most foreign nationals entering India need a valid passport and visa; eligibility and visa type depend on nationality and purpose. Start only at the official Indian government portal or an Indian mission, and verify the current rule for the traveler's passport.", "verified", _profile("visa", "before_trip")),
    ("India e-Visa application", "India", ["evisa India", "Indian e visa", "apply India visa"], "visa", "visa_info",
     "Eligible travelers can apply for an India e-Visa online through indianvisaonline.gov.in. The official application process uses a passport bio page and a recent photograph; fees and eligible nationalities vary, so the live portal is the source of truth.", "verified", _profile("visa", "before_trip")),
    ("India passport validity", "India", ["passport validity India", "blank pages India visa"], "visa", "visa_info",
     "The official India visa guidance says a passport should normally have at least six months validity and two blank pages for immigration stamps. Check the exact visa and nationality rules before departure.", "verified", _profile("visa", "before_trip")),
    ("India e-Arrival card", "India", ["e arrival card India", "India arrival form", "arrival card"], "visa", "arrival_info",
     "Foreigners and OCI cardholders must complete the India e-Arrival Card online within 72 hours before arrival; it is arrival information, not a visa. Use the official portal and do not pay an intermediary for the form.", "verified", _profile("arrival", "before_trip")),
    ("India visa fraud warning", "India", ["fake India visa website", "visa agent scam", "express visa fee"], "visa", "safety_info",
     "The Bureau of Immigration warns that the Government of India does not authorize agents or intermediaries to charge emergency or express fees for e-Visas or e-Arrival Cards. Use the official government domain and keep the receipt and application number.", "verified", _profile("safety", "before_trip")),
    ("India yellow-fever entry rule", "India", ["yellow fever India", "vaccination certificate India entry"], "incredible_faq", "health_info",
     "Travelers arriving from a yellow-fever-risk country, or who recently visited one, may need a valid yellow-fever vaccination certificate. Confirm the current requirement with the official India guidance and a travel-health clinician before departure.", "verified", _profile("health", "before_trip", medical="consult_clinician")),
    ("India customs arrival declaration", "India", ["India customs", "declare baggage India", "Atithi customs"], "customs", "arrival_info",
     "International arrivals clear immigration first, collect baggage, and then pass through Customs. CBIC's ATITHI platform allows travelers to file baggage and currency declarations before or after landing, before entering the Green Channel.", "verified", _profile("arrival", "before_trip")),
    ("India customs green or red channel", "India", ["red channel India airport", "green channel customs India"], "customs", "arrival_info",
     "Use the Green Channel only when you have nothing dutiable or restricted to declare; use the Red Channel and ask Customs when unsure. Keep receipts and check the current baggage allowance instead of relying on old travel advice.", "verified", _profile("arrival", "arrival_day")),
    ("India tourist helpline", "India", ["1363", "tourist help India", "foreign tourist help"], "tourist_help", "safety_info",
     "India's Ministry of Tourism operates a 24-hour multilingual tourist helpline on 1800-11-1363 or short code 1363 for travel information and guidance to tourists in distress. Save it before landing; availability and routing should be confirmed on the official page.", "verified", _profile("safety", "during_trip")),
    ("India emergency number 112", "India", ["police India", "ambulance India", "fire India", "emergency 112"], "emergency", "safety_info",
     "Dial 112 in an emergency in India for integrated police, fire, medical, and other emergency response. Give your exact location, landmark, callback number, and whether anyone is injured; use the local emergency system rather than waiting for an app.", "verified", _profile("safety", "during_trip", action="call_112")),
    ("India 112 safety app", "India", ["112 India app", "panic button India", "women safety 112"], "emergency", "safety_info",
     "The Government of India's ERSS describes the 112 India app and phone panic activation as additional ways to raise an SOS with location information. Test access before a trip, but call 112 directly for an immediate emergency.", "verified", _profile("safety", "before_and_during_trip", action="call_112")),
    ("Booking Indian trains", "India", ["book train India", "IRCTC train tickets", "Indian Railway tickets"], "rail", "transport_info",
     "Air, rail, and road are India's main visitor transport modes. For trains, Incredible India points travelers to the official IRCTC website; check the exact station, date, class, passenger name, and cancellation terms before paying.", "verified", _profile("transport", "before_trip")),
    ("Foreign tourist train quota", "India", ["foreign tourist train booking", "FT quota IRCTC", "IRCTC foreigner"], "rail", "transport_info",
     "IRCTC provides a Foreign Tourist Quota flow for eligible foreign tourists and NRIs. It requires a registered international mobile number and passport details; rules, advance windows, classes, fees, and availability can change, so confirm on the current IRCTC guide.", "verified", _profile("transport", "before_trip")),
    ("Passport on Indian train journeys", "India", ["passport train India", "visa ID train India"], "rail", "transport_info",
     "A foreign tourist using a Foreign Tourist Quota booking must carry the original passport and valid visa corresponding to the booking details. Keep a secure digital copy separately, but do not assume a screenshot replaces the original document.", "verified", _profile("transport", "during_trip", document="passport_and_visa")),
    ("India currency and exchange", "India", ["Indian rupees", "exchange money India", "currency India"], "incredible_faq", "payment_info",
     "India uses the Indian rupee (INR). Incredible India advises exchanging foreign currency at airports, hotels, RBI-approved money changers, and selected banks; compare the displayed rate and keep the receipt rather than using an unknown street exchanger.", "verified", _profile("payments", "arrival_day")),
    ("India first-time payment plan", "India", ["pay in India", "cash or card India", "UPI tourist"], "incredible_faq", "payment_info",
     "Carry a small INR cash reserve, one primary card, one backup payment method, and notify your card issuer before travel. Cards and digital payments are common in cities, but small vendors, rural areas, transport, and connectivity gaps can still require cash.", "estimated", _profile("payments", "before_and_during_trip", priority="high")),
    ("Foreign visitor India SIM", "India", ["SIM card India foreigner", "tourist SIM India", "mobile data India"], "telecom", "connectivity_info",
     "Department of Telecommunications guidance says a foreign tourist can use a passport with a valid visa as identity proof for a mobile connection; the connection validity must not exceed the visa period and is limited to three months at a time. Buy from an authorized operator outlet and keep the KYC receipt.", "verified", _profile("connectivity", "arrival_day", document="passport_and_visa")),
    ("India connectivity backup", "India", ["WiFi India travel", "internet India tourist", "offline maps India"], "incredible_faq", "connectivity_info",
     "Travelers can use local mobile data, portable Wi-Fi, or hotel and café Wi-Fi. Download offline maps, hotel address, tickets, translation phrases, and emergency contacts before leaving airport Wi-Fi; coverage changes across mountains, islands, parks, and rural roads.", "verified", _profile("connectivity", "before_trip")),
    ("Languages in India", "India", ["language India travel", "English in India", "Hindi travel"], "incredible_faq", "culture_info",
     "India is linguistically diverse, and English is widely used in tourism and many transport, hotel, and service contexts, but it is not guaranteed everywhere. Save the destination name, hotel address, and important instructions in both English and the local script when possible.", "verified", _profile("culture", "before_and_during_trip")),
    ("Religious-place clothing in India", "India", ["temple dress code India", "mosque dress India", "what to wear India"], "incredible_faq", "culture_info",
     "Dress modestly at temples, mosques, gurdwaras, monasteries, churches, and other religious places. Ask about covering shoulders or legs, remove footwear where requested, and follow each site's posted rules rather than assuming one rule applies everywhere.", "verified", _profile("culture", "during_trip")),
    ("Photography and worship etiquette", "India", ["photo permission India", "can I take photos temple", "Indian culture etiquette"], "incredible_culture", "culture_info",
     "A religious site is an active place of worship, not only a sightseeing object. Ask before photographing people, ceremonies, homes, artisans, or worshippers; obey no-photo signs and never interrupt a prayer or ritual for a picture.", "estimated", _profile("culture", "during_trip")),
    ("Regional Indian food orientation", "India", ["food India beginner", "what food India", "Indian cuisine regions"], "incredible_culture", "food_info",
     "Indian food changes by region: northern cuisines often feature breads and rich gravies, southern cuisines commonly use rice, coconut, and curry leaves, western regions have strong vegetarian traditions, and the Northeast has distinct local ingredients and smoked or fermented foods. Treat the country as many food regions, not one menu.", "verified", _profile("food", "before_and_during_trip")),
    ("Food allergy and dietary request", "India", ["vegetarian India", "vegan India", "Jain food India", "food allergy India"], "incredible_faq", "food_info",
     "Tell the restaurant exactly what you cannot eat and ask about shared oil, ghee, dairy, nuts, and cross-contact; carry the request written in English and the local language. “Vegetarian,” “vegan,” “Jain,” and allergy-safe are different requests and should not be treated as interchangeable.", "estimated", _profile("food", "during_trip", medical="allergy_awareness")),
    ("Safe food and water in India", "India", ["drink tap water India", "street food safety India", "Delhi belly"], "health", "health_info",
     "CDC advises travelers to make safe food and drink choices, wash hands, and avoid contaminated water. For a first trip, choose sealed bottled or reliably filtered water, check the seal, eat food that is hot and freshly prepared, and seek medical care if severe illness develops.", "verified", _profile("health", "during_trip", medical="consult_clinician")),
    ("Mosquito and insect protection in India", "India", ["mosquito India travel", "dengue India", "malaria India"], "health", "health_info",
     "Mosquitoes can transmit diseases in India. CDC recommends covering exposed skin, using an appropriate repellent as directed, and using screened or air-conditioned rooms or a bed net where needed; ask a clinician whether destination-specific medication is appropriate.", "verified", _profile("health", "before_and_during_trip", medical="consult_clinician")),
    ("India travel health appointment", "India", ["vaccines for India", "doctor before India trip", "travel clinic India"], "health", "health_info",
     "CDC recommends checking routine vaccinations and consulting a travel-health clinician before travel; needs depend on the person's health, destination, duration, and activities. Zentrip should provide reminders and links, not diagnose or prescribe.", "verified", _profile("health", "before_trip", medical="consult_clinician")),
    ("Heat, altitude, and weather planning", "India", ["India heat travel", "altitude India", "monsoon travel India"], "health", "health_info",
     "Heat illness and cold or altitude exposure can both be serious in India. Build midday shade and hydration breaks in hot plains, acclimatise before strenuous high-altitude activity, and check current IMD weather and local closure notices before outdoor plans.", "estimated", _profile("health", "before_and_during_trip", medical="risk_screening")),
    ("India travel insurance", "India", ["insurance for India trip", "medical evacuation India", "travel insurance"], "health", "planning_info",
     "For remote, high-altitude, island, wildlife, or adventure trips, compare insurance for medical care, evacuation, cancellation, baggage, and the activities being undertaken. Keep the assistance number and policy copy offline; insurance terms are contractual and must be checked by the traveler.", "estimated", _profile("planning", "before_trip", priority="medium")),
    ("Protected and restricted areas India", "India", ["permit India travel", "protected area permit", "restricted area India"], "incredible_faq", "planning_info",
     "Some Indian regions designated Protected or Restricted require permits or additional permissions. Check the destination authority, permitted route, identity documents, and current access before booking transport or promising a day trip.", "verified", _profile("planning", "before_trip")),
    ("India traffic and transfer buffer", "India", ["traffic India travel", "how much transfer time India", "road travel India"], "incredible_faq", "planning_info",
     "India's distances can look short on a map but road traffic, city congestion, hill roads, monsoon, festivals, security checks, and last-mile transfers change actual travel time. Do not schedule an important flight, train, or monument entry with zero buffer after a road transfer.", "estimated", _profile("planning", "before_and_during_trip", priority="high")),
    ("Responsible wildlife and community travel", "India", ["ethical safari India", "responsible tourism India", "local guide India"], "sustainable", "culture_info",
     "Incredible India's Travel for LiFE guidance asks visitors to respect local culture and heritage, follow protected-area protocols, avoid wildlife exploitation, support local operators and artisans, and never pressure guides to guarantee an animal sighting.", "verified", _profile("culture", "during_trip")),
    ("India first-day arrival checklist", "India", ["first day India", "India arrival checklist", "landing in India"], "incredible_faq", "arrival_info",
     "On arrival, keep your passport, visa or OCI document, hotel address, emergency contacts, payment backup, and a charged phone accessible. Confirm your airport pickup by the vehicle registration or official desk, then share your first hotel check-in with a trusted contact.", "estimated", _profile("arrival", "arrival_day", priority="high")),
    ("India public holidays and festivals", "India", ["India holidays", "Diwali travel", "Holi travel", "festival crowds India"], "incredible_faq", "planning_info",
     "India's public holidays and regional festivals can close, restrict, or overcrowd monuments, offices, roads, temples, and transport. Check the official holiday calendar and local event notices for the travel year before fixing a tight itinerary.", "verified", _profile("planning", "before_trip", priority="high")),
    ("India airport and flight planning", "India", ["India airport guide", "airport transfer India", "domestic flight India"], "incredible_faq", "transport_info",
     "Incredible India's airport directory organizes airports by region and state and identifies major gateways. Match the airport code to the city, allow time for security and terminal transfers, and recheck the airline's current baggage and check-in rules.", "verified", _profile("transport", "before_and_during_trip")),
    ("India authorized travel partners", "India", ["India travel agent", "authorized tour operator India", "book guide India"], "incredible_faq", "planning_info",
     "The Incredible India travel-partner directory can filter providers by state, service type, and specialties such as ticketing, transport, adventure sports, document processing, and languages. Use it as a discovery source, then verify the provider's current credentials, inclusions, cancellation terms, and reviews before paying.", "verified", _profile("planning", "before_trip")),
    ("Accessible India trip planning", "India", ["wheelchair India travel", "accessible tourism India", "disabled traveler India"], "incredible_faq", "planning_info",
     "Accessibility varies widely between airports, hotels, roads, temples, forts, boats, and heritage sites. Ask each supplier for step-free entry, lift dimensions, accessible toilets, vehicle boarding, room details, and assistance in writing; never infer accessibility from a star rating or a short description.", "estimated", _profile("planning", "before_trip", priority="high", accessibility="supplier_confirmation")),
    ("India booking and document folder", "India", ["India travel documents", "offline travel documents", "India itinerary backup"], "incredible_faq", "planning_info",
     "Keep offline copies of passport identity page, visa or OCI, insurance, tickets, hotel confirmations, emergency contacts, prescriptions, and a trusted-contact itinerary. Store copies securely and share only what a legitimate provider needs; never share card PINs, passwords, or OTPs.", "estimated", _profile("planning", "before_trip", priority="high", privacy="minimize_sensitive_data")),
]
