"""Additional destination anchors for the national tourism layer.

This batch fills high-demand regional gaps. Claims are intentionally concise;
operational hours, permits, prices, and closures belong in observations.
"""

SOURCES = {
    "incredible_india": ("Incredible India — Regional Destination Guides", "https://www.incredibleindia.gov.in/en", "official", "primary"),
    "up": ("Incredible India — Uttar Pradesh", "https://www.incredibleindia.gov.in/en/uttar-pradesh", "official", "primary"),
    "odisha": ("Incredible India — Odisha", "https://www.incredibleindia.gov.in/en/odisha", "official", "primary"),
    "kerala": ("Incredible India — Kerala", "https://www.incredibleindia.gov.in/en/kerala", "official", "primary"),
    "rajasthan": ("Incredible India — Rajasthan", "https://www.incredibleindia.gov.in/en/rajasthan", "official", "primary"),
    "karnataka": ("Incredible India — Karnataka", "https://www.incredibleindia.gov.in/en/karnataka", "official", "primary"),
    "gujarat": ("Incredible India — Gujarat", "https://www.incredibleindia.gov.in/en/gujarat", "official", "primary"),
    "maharashtra": ("Incredible India — Maharashtra", "https://www.incredibleindia.gov.in/en/maharashtra", "official", "primary"),
    "madhya_pradesh": ("Incredible India — Madhya Pradesh", "https://www.incredibleindia.gov.in/en/madhya-pradesh", "official", "primary"),
    "himachal": ("Incredible India — Himachal Pradesh", "https://www.incredibleindia.gov.in/en/himachal-pradesh", "official", "primary"),
    "uttarakhand": ("Incredible India — Uttarakhand", "https://www.incredibleindia.gov.in/en/uttarakhand", "official", "primary"),
}


def _profile(tags: list[str], duration: int, season: str, notes: str) -> dict:
    return {"tags": tags, "durationMinutes": duration, "energy": "medium", "season": season, "walking": "medium", "notes": notes}


# (name, city, aliases, source_key, entity_type, claim, experience_profile)
ENTRIES = [
    ("Mathura–Vrindavan Braj Circuit", "Mathura", ["Vrindavan", "Braj", "Krishna circuit"], "up", "activity", "Mathura and its twin city Vrindavan form the heart of Braj Bhoomi, combining living Krishna temples, riverfront traditions, local art, and nearby Govardhan pilgrimage routes.", _profile(["spiritual", "culture", "food", "walking"], 480, "October–March is generally more comfortable; festival crowds vary.", "Treat temples as active worship spaces; narrow lanes and crowd controls require buffer.")),
    ("Lucknow Nawabi Heritage and Food", "Lucknow", ["Lucknow", "Awadh", "Nawabi city"], "up", "activity", "Lucknow is a major Uttar Pradesh heritage and food city, known for Nawabi-era architecture, chikankari craft, gardens, and Awadhi cuisine.", _profile(["heritage", "food", "craft", "culture"], 480, "October–March is generally more comfortable for outdoor heritage walks.", "Plan food and monument visits separately; heat and traffic make midday walking slower.")),
    ("Ayodhya Sarayu and Temple Circuit", "Ayodhya", ["Ayodhya", "Sarayu", "Ram temple"], "up", "activity", "Ayodhya is a major spiritual destination on the Sarayu, with temple precincts, riverfront activity, and access rules that can change during festivals and high-demand periods.", _profile(["spiritual", "culture", "river", "family"], 360, "October–March is generally more comfortable; religious calendar crowds vary.", "Follow security, queue, dress, footwear, and photography rules at each religious site.")),
    ("Bhubaneswar Temple and Cave Circuit", "Bhubaneswar", ["Bhubaneswar", "Lingaraj", "Udayagiri Khandagiri"], "odisha", "activity", "Bhubaneswar combines ancient temples, Jain rock-cut caves, museums, crafts, and a practical gateway to Puri and Konark on Odisha's coast.", _profile(["heritage", "spiritual", "architecture", "food"], 480, "October–March is generally more comfortable; summer afternoons are hot.", "Some temples restrict entry to non-Hindus; verify site-specific access and dress rules.")),
    ("Puri Jagannath and Chilika Coast", "Puri", ["Puri", "Jagannath", "Chilika Lake"], "odisha", "activity", "Puri is a major coastal pilgrimage destination associated with Jagannath, beaches, crafts, and nearby Chilika and Konark experiences.", _profile(["spiritual", "beach", "food", "nature"], 720, "October–March is generally easier; monsoon and cyclone conditions affect coastal plans.", "Non-Hindu entry restrictions apply at some temples; use registered boat operators on Chilika.")),
    ("Wayanad Forest and Coffee Circuit", "Wayanad", ["Wayanad", "Edakkal Caves", "Banasura Sagar"], "kerala", "activity", "Wayanad is a highland Kerala landscape of forests, coffee and spice country, caves, waterfalls, dams, and wildlife edges, with long road transfers between sights.", _profile(["nature", "coffee", "wildlife", "adventure"], 720, "October–May is commonly easier; monsoon creates dramatic scenery but can restrict travel.", "Use local guides on trails and check forest closures, leeches, rain, and road conditions.")),
    ("Varkala Cliff and Beach Retreat", "Varkala", ["Varkala", "Papanasam Beach", "Sivagiri"], "kerala", "activity", "Varkala combines a geological cliff above the Arabian Sea, beach time, the Janardhana Swamy Temple, and Sivagiri heritage in a compact coastal base.", _profile(["beach", "wellness", "spiritual", "slow travel"], 480, "October–March is the classic beach and walking window.", "Cliff edges and sea conditions need care; follow beach warnings and temple etiquette.")),
    ("Udaipur Lakes and Palace Circuit", "Udaipur", ["Udaipur", "Lake Pichola", "City Palace Udaipur"], "rajasthan", "activity", "Udaipur is organised around Lake Pichola and the City Palace waterfront, with lakes, palace museums, hill viewpoints, craft shopping, and nearby Aravalli excursions.", _profile(["heritage", "lakes", "photography", "food"], 720, "October–March is generally more comfortable; monsoon makes the lakes greener.", "Boat departures, palace access, and sunset viewpoints should be checked on the day.")),
    ("Mount Abu Hill and Jain Heritage", "Mount Abu", ["Mount Abu", "Dilwara temples", "Nakki Lake"], "rajasthan", "activity", "Mount Abu is Rajasthan's hill station, combining forested Aravalli scenery, Nakki Lake, viewpoints, and the intricately carved Dilwara Jain temples.", _profile(["mountains", "spiritual", "nature", "architecture"], 720, "November–February is popular; July–September is greener and wetter.", "Roads are winding; temple photography and entry rules must be respected.")),
    ("Coorg Coffee and Western Ghats Escape", "Coorg", ["Kodagu", "Coorg", "coffee country Karnataka"], "karnataka", "activity", "Coorg is a Western Ghats coffee-and-forest destination with plantation experiences, waterfalls, viewpoints, and Kodava cultural context.", _profile(["nature", "coffee", "slow travel", "food"], 720, "October–May is commonly easier; monsoon is lush but wet.", "Distances are dispersed; use licensed guides for plantations and forest activities.")),
    ("Shravanabelagola Jain Heritage", "Shravanabelagola", ["Gommateshwara", "Bahubali", "Shravanbelagola"], "karnataka", "activity", "Shravanabelagola is a major Jain heritage destination centred on the monolithic Gommateshwara at Vindhyagiri, reached by a substantial hill climb.", _profile(["spiritual", "heritage", "architecture", "walking"], 360, "October–February is generally more comfortable for the exposed climb.", "The climb is strenuous and footwear rules apply; plan water, shade, and mobility support.")),
    ("Dwarka Coastal Pilgrimage", "Dwarka", ["Dwarkadhish", "Devbhumi Dwarka", "Dwarka temple"], "gujarat", "activity", "Dwarka is a Gujarat pilgrimage city associated with Dwarkadhish and coastal heritage, with temple visits and nearby marine-archaeology narratives.", _profile(["spiritual", "coast", "heritage", "family"], 480, "November–February is generally the most comfortable outdoor window.", "Temple queues and access rules vary; separate pilgrimage time from coastal sightseeing.")),
    ("Visakhapatnam and Araku Valley", "Visakhapatnam", ["Vizag", "Araku", "Andhra coast"], "incredible_india", "activity", "Visakhapatnam combines an urban Bay of Bengal coast with beaches, museums, viewpoints, and a rail/road extension into the forested Araku Valley.", _profile(["coast", "nature", "food", "rail"], 960, "October–March is generally more comfortable; cyclone and monsoon alerts affect coastal plans.", "Allow a full day for Araku transfers and verify rail operations before promising the scenic route.")),
    ("Ooty Nilgiri Mountain Retreat", "Ooty", ["Udhagamandalam", "Nilgiris", "Ooty toy train"], "incredible_india", "activity", "Ooty is a Nilgiri hill station known for cool climate, tea landscapes, gardens, lakes, and the heritage mountain-railway experience.", _profile(["mountains", "tea", "family", "rail"], 720, "October–June is commonly planned; monsoon brings rain and mist.", "Hill roads and toy-train seats are capacity constrained; keep a weather buffer.")),
    ("Tirupati Temple Pilgrimage", "Tirupati", ["Tirumala", "Venkateswara", "Tirupati temple"], "incredible_india", "activity", "Tirupati and Tirumala form one of India's major pilgrimage destinations, where darshan, accommodation, queues, and transport are governed by temple-board systems.", _profile(["spiritual", "family", "culture"], 720, "October–March is generally more comfortable; festival demand can be extreme.", "Book only through the official temple system and never promise a darshan slot without confirmation.")),
    ("Mumbai Heritage and Coast Circuit", "Mumbai", ["Bombay", "Mumbai", "Gateway of India", "Marine Drive"], "maharashtra", "activity", "Mumbai combines colonial and Art Deco heritage, waterfront promenades, markets, museums, and a dense local food culture across a large, fast-moving metropolis.", _profile(["heritage", "architecture", "food", "coast"], 960, "November–February is generally more comfortable for outdoor city days; monsoon changes waterfront conditions.", "Use rail or metro where practical, allow traffic buffers, and separate heritage walking from late-night travel.")),
    ("Ajanta Ellora Cave Heritage Circuit", "Aurangabad", ["Chhatrapati Sambhajinagar", "Ajanta Caves", "Ellora Caves", "Verul"], "maharashtra", "activity", "Ajanta and Ellora are distinct archaeological landscapes: Ajanta's Buddhist rock-cut caves and Ellora's Buddhist, Hindu, and Jain monuments need separate transfer and site time.", _profile(["heritage", "archaeology", "architecture", "photography"], 1440, "October–March is generally more comfortable for the outdoor approaches; heat affects exposed walks.", "Do not compress both sites into a rushed day; verify weekly closures, official tickets, and site transport.")),
    ("Khajuraho Temples and Panna Circuit", "Khajuraho", ["Khajuraho", "Panna Tiger Reserve", "Chhatarpur"], "madhya_pradesh", "activity", "Khajuraho's temple groups provide a concentrated heritage base, while nearby Panna adds a separate wildlife and river landscape with its own permits and timings.", _profile(["heritage", "architecture", "wildlife", "photography"], 1440, "October–March is generally the most comfortable combined heritage-and-wildlife window; summer heat is intense.", "Treat temple sightseeing and safari as separate bookings; never guarantee wildlife sightings or a same-day transfer.")),
    ("Manali Valley and Rohtang Gateway", "Manali", ["Manali", "Rohtang Pass", "Solang Valley", "Himachal"], "himachal", "activity", "Manali is a Himalayan valley base for local culture, river landscapes, short walks, and seasonal high-road excursions whose permits and weather conditions can change quickly.", _profile(["mountains", "nature", "adventure", "photography"], 2880, "March–June and October–November are common valley planning windows; snow and monsoon affect high roads.", "Acclimatise before strenuous activity, verify road permits and closures, and keep a weather buffer for Rohtang routes.")),
    ("Mussoorie and Dehradun Foothill Escape", "Mussoorie", ["Mussoorie", "Dehradun", "Queen of the Hills", "Landour"], "uttarakhand", "activity", "Mussoorie is a hill-town base for viewpoints, colonial-era lanes, forest walks, and a Dehradun gateway, with weekend traffic often shaping the experience more than distance suggests.", _profile(["mountains", "nature", "slow travel", "family"], 1440, "March–June and September–November are common comfortable windows; monsoon brings rain and road disruption.", "Use short walking loops, avoid cliff edges, and allow extra road time during weekends and school holidays.")),
    ("Hampi Vijayanagara Heritage Landscape", "Hampi", ["Hampi", "Vijayanagara", "Virupaksha Temple"], "karnataka", "activity", "Hampi is an extensive archaeological and living cultural landscape of Vijayanagara-era monuments, temples, boulder hills, and dispersed village routes rather than a single walkable monument.", _profile(["heritage", "architecture", "history", "photography"], 1440, "October–February is generally more comfortable for the exposed heritage landscape; summer heat is severe.", "Hire a licensed local guide, plan by zone, respect active temples, and do not cycle exposed roads in peak heat.")),
    ("Nashik Godavari and Vineyard Circuit", "Nashik", ["Nasik", "Nashik vineyards", "Godavari Nashik", "Trimbakeshwar"], "maharashtra", "activity", "Nashik combines Godavari and pilgrimage heritage with vineyards and food experiences spread across a broad road network, requiring a choice between city, temple, and countryside bases.", _profile(["food", "spiritual", "nature", "slow travel"], 960, "October–February is generally comfortable; monsoon is greener but can affect vineyard and road plans.", "Separate wine tourism from pilgrimage etiquette and use a designated driver or trusted transport.")),
    ("Auli and Joshimath Himalayan Base", "Auli", ["Auli", "Joshimath", "Gorson Bugyal"], "uttarakhand", "activity", "Auli is a high Himalayan meadow and winter-sports base reached through Joshimath, with seasonal snow, ropeway operations, trekking routes, and weather-sensitive road access.", _profile(["mountains", "nature", "adventure", "photography"], 2880, "December–March suits snow activities; April–June and September–November suit clearer non-snow mountain travel.", "Check ropeway and road operations, plan altitude-aware pacing, and use local guides for meadow routes.")),
]


PROFILES = [
    ("Mathura–Vrindavan Braj Circuit", "Uttar Pradesh", "North", "spiritual_city", ["spiritual", "culture", "food", "walking"], ["October–March"], 2, 3, 174, "Delhi", ["DEL"], "Delhi/Agra gateways with regional road and rail connections.", "Festival crowds, heat, narrow lanes, and active worship rules affect access.", {"walking": "high", "wheelchair": "limited", "family": "medium"}, "up"),
    ("Lucknow Nawabi Heritage and Food", "Uttar Pradesh", "North", "heritage_city", ["heritage", "food", "craft", "culture"], ["October–March"], 2, 3, 123, "Lucknow", ["LKO"], "Strong airport and rail gateway for central Uttar Pradesh.", "Heat, traffic, and crowded markets require flexible pacing.", {"walking": "medium", "wheelchair": "medium", "family": "high"}, "up"),
    ("Ayodhya Sarayu and Temple Circuit", "Uttar Pradesh", "North", "pilgrimage", ["spiritual", "culture", "river", "family"], ["October–March"], 1, 3, 93, "Lucknow", ["LKO"], "Lucknow or Ayodhya airport/rail gateway; verify local transfers.", "Security, queues, festivals, and religious-site rules change quickly.", {"walking": "high", "wheelchair": "limited", "family": "medium"}, "up"),
    ("Bhubaneswar Temple and Cave Circuit", "Odisha", "East", "heritage_city", ["heritage", "spiritual", "architecture", "food"], ["October–March"], 2, 3, 45, "Bhubaneswar", ["BBI"], "Air and rail gateway for Odisha's temple coast.", "Heat and temple entry restrictions require site-by-site checks.", {"walking": "medium", "wheelchair": "medium", "family": "medium"}, "odisha"),
    ("Puri Jagannath and Chilika Coast", "Odisha", "East", "coastal_pilgrimage", ["spiritual", "beach", "food", "nature"], ["October–March"], 2, 4, 10, "Bhubaneswar", ["BBI"], "Bhubaneswar gateway with road/rail to Puri and boat extensions.", "Cyclones, monsoon seas, temple access, and boat safety matter.", {"walking": "medium", "wheelchair": "limited", "family": "medium"}, "odisha"),
    ("Wayanad Forest and Coffee Circuit", "Kerala", "South", "highland_nature", ["nature", "coffee", "wildlife", "adventure"], ["October–May"], 3, 5, 800, "Kozhikode", ["CCJ"], "Kozhikode airport/rail gateway with winding hill road.", "Monsoon, forest closures, wildlife, and trail conditions vary.", {"walking": "high", "wheelchair": "limited", "family": "low"}, "kerala"),
    ("Varkala Cliff and Beach Retreat", "Kerala", "South", "coastal", ["beach", "wellness", "spiritual", "slow travel"], ["October–March"], 2, 4, 30, "Thiruvananthapuram", ["TRV"], "Thiruvananthapuram airport/rail gateway.", "Cliff edges, surf, heat, and religious-site rules require care.", {"walking": "medium", "wheelchair": "limited", "family": "medium"}, "kerala"),
    ("Udaipur Lakes and Palace Circuit", "Rajasthan", "North", "heritage_city", ["heritage", "lakes", "photography", "food"], ["October–March"], 2, 4, 598, "Udaipur", ["UDR"], "Udaipur airport and rail gateway for southern Rajasthan.", "Boat schedules, heat, and palace access change with conditions.", {"walking": "medium", "wheelchair": "medium", "family": "medium"}, "rajasthan"),
    ("Mount Abu Hill and Jain Heritage", "Rajasthan", "North", "hill_station", ["mountains", "spiritual", "nature", "architecture"], ["November–February"], 2, 3, 1220, "Udaipur", ["UDR"], "Udaipur or Ahmedabad gateway, then road to Abu Road/Mount Abu.", "Winding roads and hill walking affect accessibility.", {"walking": "high", "wheelchair": "limited", "family": "medium"}, "rajasthan"),
    ("Coorg Coffee and Western Ghats Escape", "Karnataka", "South", "highland_nature", ["nature", "coffee", "slow travel", "food"], ["October–May"], 3, 5, 1170, "Mangaluru", ["IXE"], "Mangaluru, Mysuru, or Bengaluru gateways with road transfer.", "Rain, winding roads, and dispersed estates require buffers.", {"walking": "medium", "wheelchair": "limited", "family": "medium"}, "karnataka"),
    ("Shravanabelagola Jain Heritage", "Karnataka", "South", "pilgrimage", ["spiritual", "heritage", "architecture", "walking"], ["October–February"], 1, 2, 880, "Bengaluru", ["BLR"], "Bengaluru gateway with rail/road transfer.", "Exposed hill climb and footwear rules make mobility planning important.", {"walking": "high", "wheelchair": "limited", "family": "low"}, "karnataka"),
    ("Dwarka Coastal Pilgrimage", "Gujarat", "West", "coastal_pilgrimage", ["spiritual", "coast", "heritage", "family"], ["November–February"], 2, 3, 15, "Jamnagar", ["JGA"], "Jamnagar/Rajkot/Ahmedabad gateways with road/rail extensions.", "Temple queues, heat, and coastal conditions change the day plan.", {"walking": "medium", "wheelchair": "medium", "family": "medium"}, "gujarat"),
    ("Visakhapatnam and Araku Valley", "Andhra Pradesh", "South", "coastal_nature", ["coast", "nature", "food", "rail"], ["October–March"], 3, 5, 45, "Visakhapatnam", ["VTZ"], "Airport and rail gateway; Araku requires a long mountain transfer.", "Cyclone alerts, monsoon, and scenic-rail availability require checks.", {"walking": "medium", "wheelchair": "limited", "family": "medium"}, "incredible_india"),
    ("Ooty Nilgiri Mountain Retreat", "Tamil Nadu", "South", "hill_station", ["mountains", "tea", "family", "rail"], ["October–June"], 2, 4, 2240, "Coimbatore", ["CJB"], "Coimbatore airport/rail gateway with hill road or heritage rail.", "Road weather, train capacity, and altitude affect accessibility.", {"walking": "medium", "wheelchair": "limited", "family": "medium"}, "incredible_india"),
    ("Tirupati Temple Pilgrimage", "Andhra Pradesh", "South", "pilgrimage", ["spiritual", "family", "culture"], ["October–March"], 1, 3, 150, "Tirupati", ["TIR"], "Tirupati airport/rail gateway; Tirumala is a separate hill transfer.", "Darshan, accommodation, queues, and festivals are booking-dependent.", {"walking": "high", "wheelchair": "medium", "family": "medium"}, "incredible_india"),
    ("Mumbai Heritage and Coast Circuit", "Maharashtra", "West", "heritage_city", ["heritage", "architecture", "food", "coast"], ["November–February"], 2, 4, 14, "Mumbai", ["BOM"], "Major air and rail gateway; city rail/metro and ferries serve different zones.", "Monsoon, traffic, heat, and late-night transport require flexible routing.", {"walking": "medium", "wheelchair": "medium", "family": "medium"}, "maharashtra"),
    ("Ajanta Ellora Cave Heritage Circuit", "Maharashtra", "West", "archaeology", ["heritage", "archaeology", "architecture", "photography"], ["October–March"], 2, 3, 600, "Aurangabad", ["IXU"], "Aurangabad/Chhatrapati Sambhajinagar gateway with separate road transfers to Ajanta and Ellora.", "Weekly closures, heat, uneven surfaces, and long transfers affect the combined circuit.", {"walking": "high", "wheelchair": "limited", "family": "medium"}, "maharashtra"),
    ("Khajuraho Temples and Panna Circuit", "Madhya Pradesh", "Central", "heritage_wildlife", ["heritage", "architecture", "wildlife", "photography"], ["October–March"], 2, 4, 283, "Khajuraho", ["HJR"], "Khajuraho airport/rail gateway; Panna requires a separate road and permit plan.", "Heat, safari permits, park closures, and wildlife uncertainty require buffers.", {"walking": "medium", "wheelchair": "medium", "family": "medium"}, "madhya_pradesh"),
    ("Manali Valley and Rohtang Gateway", "Himachal Pradesh", "North", "mountain_valley", ["mountains", "nature", "adventure", "photography"], ["March–June", "October–November"], 3, 5, 2050, "Manali", ["KUU"], "Kullu airport/road gateway; high-road excursions are seasonal and permit-controlled.", "Altitude, snow, landslides, road closures, and adventure-operator safety require checks.", {"walking": "high", "wheelchair": "limited", "family": "medium"}, "himachal"),
    ("Mussoorie and Dehradun Foothill Escape", "Uttarakhand", "North", "hill_station", ["mountains", "nature", "slow travel", "family"], ["March–June", "September–November"], 2, 4, 2005, "Dehradun", ["DED"], "Dehradun airport/rail gateway with a winding hill road to Mussoorie.", "Weekend traffic, monsoon roads, slopes, and cliff edges affect access.", {"walking": "medium", "wheelchair": "limited", "family": "medium"}, "uttarakhand"),
    ("Hampi Vijayanagara Heritage Landscape", "Karnataka", "South", "archaeology", ["heritage", "architecture", "history", "photography"], ["October–February"], 2, 4, 467, "Hospet", ["VDY"], "Hospet rail/road gateway; monuments are dispersed across a wide landscape.", "Heat, uneven terrain, active temples, and dispersed transfers require zone-based planning.", {"walking": "high", "wheelchair": "limited", "family": "medium"}, "karnataka"),
    ("Nashik Godavari and Vineyard Circuit", "Maharashtra", "West", "food_culture", ["food", "spiritual", "nature", "slow travel"], ["October–February"], 2, 3, 565, "Nashik", ["ISK"], "Nashik road/rail gateway with dispersed vineyards and temple routes.", "Festival crowds, heat, road safety, and alcohol-free pilgrimage planning matter.", {"walking": "medium", "wheelchair": "medium", "family": "medium"}, "maharashtra"),
    ("Auli and Joshimath Himalayan Base", "Uttarakhand", "North", "high_altitude", ["mountains", "nature", "adventure", "photography"], ["December–March", "April–June", "September–November"], 2, 4, 2800, "Dehradun", ["DED"], "Dehradun/Rishikesh gateway with a long mountain road to Joshimath and Auli.", "Altitude, snow, ropeway operations, weather, and road closures are material constraints.", {"walking": "high", "wheelchair": "limited", "family": "low"}, "uttarakhand"),
]


ROUTES = [
    ("Delhi Gateway", "Mathura–Vrindavan Braj Circuit", "road", 180, 150, 300, "Traffic and festival crowds can extend the transfer.", "up"),
    ("Delhi Gateway", "Lucknow Nawabi Heritage and Food", "air", 420, 90, 180, "Flight and airport transfer schedules must be checked.", "up"),
    ("Kolkata Gateway", "Bhubaneswar Temple and Cave Circuit", "air", 440, 75, 150, "Rail is also practical; compare station and airport transfers.", "odisha"),
    ("Bhubaneswar Gateway", "Puri Jagannath and Chilika Coast", "road", 65, 120, 210, "Coastal traffic and pilgrimage crowds affect timing.", "odisha"),
    ("Kochi Gateway", "Wayanad Forest and Coffee Circuit", "road", 280, 360, 540, "Hill roads and monsoon can extend the transfer materially.", "kerala"),
    ("Jaipur Gateway", "Udaipur Lakes and Palace Circuit", "road", 395, 360, 540, "Long road leg; rail and flight alternatives should be compared.", "rajasthan"),
    ("Bengaluru Gateway", "Coorg Coffee and Western Ghats Escape", "road", 265, 330, 480, "Weekend traffic and rain affect the winding road.", "karnataka"),
    ("Ahmedabad Gateway", "Dwarka Coastal Pilgrimage", "road", 440, 480, 720, "Treat as a regional Gujarat circuit rather than a day return.", "gujarat"),
    ("Bengaluru Gateway", "Ooty Nilgiri Mountain Retreat", "road", 270, 360, 540, "Ghat roads are slow; heritage rail is capacity constrained.", "incredible_india"),
    ("Bengaluru Gateway", "Tirupati Temple Pilgrimage", "road", 250, 300, 480, "Temple booking and hill transport must be aligned.", "incredible_india"),
    ("Mumbai Gateway", "Mumbai Heritage and Coast Circuit", "mixed", 12, 30, 180, "Use local rail/metro and zone-based planning; monsoon affects ferries and waterfronts.", "maharashtra"),
    ("Mumbai Gateway", "Ajanta Ellora Cave Heritage Circuit", "air", 330, 300, 480, "Ajanta and Ellora need separate road days; do not treat them as one nearby site.", "maharashtra"),
    ("Bhopal Gateway", "Khajuraho Temples and Panna Circuit", "air", 380, 360, 600, "Coordinate heritage opening times with separate Panna safari permits.", "madhya_pradesh"),
    ("Delhi Gateway", "Manali Valley and Rohtang Gateway", "road", 540, 720, 960, "Long mountain transfer; weather and road closures can change the plan.", "himachal"),
    ("Dehradun Gateway", "Mussoorie and Dehradun Foothill Escape", "road", 35, 90, 210, "Weekend traffic can make this short route materially slower.", "uttarakhand"),
    ("Bengaluru Gateway", "Hampi Vijayanagara Heritage Landscape", "road", 340, 360, 540, "Plan Hampi by archaeological zones and keep heat buffers.", "karnataka"),
    ("Mumbai Gateway", "Nashik Godavari and Vineyard Circuit", "road", 170, 180, 300, "Choose a designated driver and separate vineyard visits from pilgrimage stops.", "maharashtra"),
    ("Dehradun Gateway", "Auli and Joshimath Himalayan Base", "road", 300, 600, 900, "Mountain road and snow operations need a large weather buffer.", "uttarakhand"),
]
