"""Pan-India destination and circuit starters for itinerary retrieval.

These are deliberately compact, high-signal records: a traveler-facing fact plus
experience metadata. Seasonal and duration guidance is labelled estimated so the
planner can personalize it without pretending it is a live schedule.
"""

SOURCES = {
    "unesco_india": ("UNESCO World Heritage Centre — India", "https://whc.unesco.org/en/statesparties/in/", "official", "primary"),
    "incredible_india": ("Incredible India, Ministry of Tourism", "https://www.incredibleindia.gov.in/en/tourism-information-centre", "official", "primary"),
    "tourism_circuits": ("Ministry of Tourism — thematic circuits", "https://www.tourism.gov.in/buddhist-circuit", "official", "primary"),
    "goa_official": ("Incredible India — Goa", "https://www.incredibleindia.gov.in/en/goa", "official", "primary"),
    "hampi_official": ("Incredible India — Hampi", "https://www.incredibleindia.gov.in/en/karnataka/hampi", "official", "primary"),
}


def _profile(tags: list[str], duration: int, energy: str, season: str, *, walking: str = "medium", budget: str = "mixed", notes: str = "") -> dict:
    return {
        "tags": tags,
        "durationMinutes": duration,
        "energy": energy,
        "walkingLevel": walking,
        "budgetLevel": budget,
        "seasonality": season,
        "planningNotes": notes,
    }


# (name, city/base, aliases, source key, entity type, fact, experience profile)
ENTRIES = [
    ("Varanasi Ganga Ghats", "Varanasi", ["Kashi ghats", "Ganga aarti", "Banaras ghats"], "incredible_india", "activity", "Varanasi is a living pilgrimage city on the Ganga; ghats, boat rides, temple lanes, and evening aarti form separate experiences rather than one single attraction.", _profile(["spiritual", "culture", "food", "photography"], 240, "high", "October–March is generally more comfortable; monsoon river levels can change access.", walking="high", notes="Use licensed boats/guides and leave buffer for dense lanes and ceremony crowds.")),
    ("Rishikesh Ganga and Ashram Circuit", "Rishikesh", ["Rishikesh", "Yoga capital", "Ganga rafting Rishikesh"], "tourism_circuits", "Rishikesh combines Ganga pilgrimage, yoga and ashram stays, suspension bridges, and seasonal white-water rafting in one Himalayan foothill base.", _profile(["spiritual", "wellness", "adventure", "nature"], 2880, "medium", "October–April for rafting and comfortable outdoor days; check river and weather closures.", walking="medium", notes="Rafting and camping are separate operator bookings; respect ashram silence and dress rules.")),
    ("Golden Temple Langar Experience", "Amritsar", ["Harmandir Sahib langar", "Amritsar Golden Temple"], "incredible_india", "The Golden Temple complex welcomes visitors of all faiths; the langar is a community kitchen experience and requires head covering, covered shoulders, and respectful conduct.", _profile(["spiritual", "community", "food", "culture"], 180, "low", "October–March is generally more comfortable; religious calendar crowds vary.", walking="medium", budget="low", notes="Remove shoes, cover the head, and follow volunteer instructions; this is worship, not a performance.")),
    ("Dal Lake and Srinagar Mughal Gardens", "Srinagar", ["Srinagar", "Kashmir Dal Lake", "Kashmir houseboat"], "incredible_india", "Srinagar is a Kashmir base for Dal Lake, houseboats, Mughal gardens, old-city heritage, and day trips toward the valley; access and weather conditions must be checked before travel.", _profile(["nature", "photography", "heritage", "slow travel"], 1440, "medium", "April–October for gardens and lake activities; winter conditions can disrupt mountain routes.", walking="medium", notes="Confirm current local advisories, transport, and houseboat licensing.")),
    ("Leh Ladakh Acclimatisation Base", "Leh", ["Ladakh", "Leh", "Indus valley"], "incredible_india", "Leh is a high-altitude base for monasteries, Indus landscapes, and mountain-road excursions; altitude acclimatisation is a safety requirement, not an optional itinerary preference.", _profile(["mountains", "culture", "road trip", "photography"], 2880, "medium", "June–September is the usual accessible road season; snow and passes can change routes.", walking="high", notes="Reserve the first day for rest, hydration, and short low-effort walks; verify permits and road status.")),
    ("Goa Coastal and Heritage Circuit", "Goa", ["Goa beaches", "Old Goa churches", "Konkan coast"], "goa_official", "Goa combines beaches, Portuguese-era churches and heritage in Old Goa, local food, and a seasonal music and nightlife economy across different talukas.", _profile(["beach", "heritage", "food", "nightlife"], 4320, "medium", "November–February is the usual dry-season window; monsoon changes beach and outdoor operations.", walking="medium", budget="mixed", notes="Choose a north, central, or south base instead of treating Goa as a single short-distance neighborhood.")),
    ("Kerala Backwaters Slow Travel", "Alappuzha", ["Alleppey backwaters", "Kerala houseboat", "Kuttanad"], "incredible_india", "The Kerala backwaters are a linked network of lagoons, canals, villages, and paddy landscapes; houseboats, canoe trips, and homestays offer different pace and impact profiles.", _profile(["slow travel", "nature", "food", "wellness"], 2880, "low", "October–March is generally the easier outdoor window; monsoon brings heavy rain but a different landscape.", walking="low", budget="mixed", notes="Compare licensed operators, inclusions, waste practices, and overnight route before paying.")),
    ("Fort Kochi Heritage Walk", "Kochi", ["Cochin", "Fort Kochi", "Mattancherry"], "incredible_india", "Fort Kochi and Mattancherry layer port history, churches, synagogues, palaces, spice-trade streets, and contemporary art over a compact coastal heritage area.", _profile(["heritage", "food", "art", "walking"], 240, "low", "October–March is generally more comfortable for walking; rain and heat affect outdoor time.", walking="high", budget="mixed", notes="Plan walking in morning/evening and verify religious-site access and photography rules.")),
    ("Munnar Tea Hills", "Munnar", ["Munnar", "Kerala tea country", "Western Ghats Munnar"], "incredible_india", "Munnar is a highland tea landscape with plantation views, short walks, waterfalls, and access to protected Western Ghats habitats; road travel is winding.", _profile(["nature", "tea", "mountains", "slow travel"], 1440, "medium", "September–May is the usual visitor window; monsoon can bring rain and road disruption.", walking="medium", notes="Do not promise wildlife sightings; check park openings and local road conditions.")),
    ("Mysuru Palace and Heritage Day", "Mysuru", ["Mysore", "Mysuru Palace", "Dasara Mysuru"], "incredible_india", "Mysuru is a palace-and-garden city whose heritage day can combine the palace, markets, temples, and nearby Chamundi Hill; Dasara creates exceptional crowds and event controls.", _profile(["heritage", "palace", "food", "family"], 480, "medium", "October–February is generally comfortable; Dasara dates change annually.", walking="medium", notes="Book accommodation early for Dasara and verify palace illumination/event schedules.")),
    ("Pondicherry French Quarter and Aurobindo Heritage", "Puducherry", ["Pondicherry", "Puducherry", "White Town"], "incredible_india", "Puducherry combines a walkable French Quarter, Tamil neighborhoods, coastal promenade, cafés, and nearby Auroville experiences that follow separate visitor rules.", _profile(["heritage", "food", "wellness", "coast"], 1440, "low", "October–March is generally more comfortable; hot months reduce midday walking.", walking="high", notes="Matrimandir access is controlled and should never be promised without a confirmed pass.")),
    ("Andaman Marine and Cellular Jail Circuit", "Port Blair", ["Andaman", "Andaman Islands", "Swaraj Dweep"], "incredible_india", "The Andaman visitor pattern combines Port Blair history, Cellular Jail, ferries, and island beaches or marine activities whose schedules depend on weather and sea conditions.", _profile(["beach", "history", "marine", "adventure"], 4320, "medium", "October–May is the usual marine-travel window; monsoon can cancel ferries and activities.", walking="medium", budget="high", notes="Keep a weather buffer for ferries and verify permits, operator insurance, and reef rules.")),
    ("Gangtok Sikkim Mountain Base", "Gangtok", ["Sikkim", "Gangtok", "Khangchendzonga gateway"], "incredible_india", "Gangtok is a Himalayan base for monasteries, viewpoints, local food, and route extensions toward north Sikkim; permits and weather govern many excursions.", _profile(["mountains", "culture", "nature", "food"], 2880, "medium", "March–May and October–November are commonly clearer; monsoon and snow can alter access.", walking="medium", notes="Check protected-area permits and road status before committing to a remote day trip.")),
    ("Meghalaya Waterfall and Living Root Bridge Circuit", "Shillong", ["Meghalaya", "Shillong", "living root bridges"], "incredible_india", "Meghalaya combines Shillong with Khasi hills, caves, waterfalls, villages, and living root bridges; many highlights require long road transfers and steep or wet walks.", _profile(["nature", "adventure", "villages", "photography"], 4320, "high", "October–April is generally easier for trails; monsoon creates dramatic waterfalls but difficult roads.", walking="high", notes="Use local guides for remote trails and do not schedule several distant waterfalls as a quick city day.")),
    ("Kaziranga Rhino Safari", "Kaziranga", ["Kaziranga National Park", "one horned rhino"], "unesco_india", "Kaziranga protects a Brahmaputra floodplain ecosystem and is internationally important for the greater one-horned rhinoceros alongside tiger, elephant, and wetland habitats.", _profile(["wildlife", "nature", "photography"], 1440, "medium", "November–April is the common safari season; flooding and park notices control access.", walking="low", budget="high", notes="Safari permits and vehicle/guide slots are separate; never guarantee an animal sighting.")),
    ("Sundarbans Mangrove Expedition", "Sundarbans", ["Sundarbans National Park", "mangrove tiger landscape"], "unesco_india", "The Sundarbans are a tidal mangrove landscape where boat-based travel, village edges, and wildlife protection rules shape the experience; this is an expedition, not a city attraction.", _profile(["wildlife", "nature", "boat", "photography"], 4320, "medium", "November–February is generally more comfortable; tides, weather, and permits control routes.", walking="low", budget="high", notes="Use registered operators, carry essential medication, and follow forest and wildlife rules.")),
    ("Ranthambore Tiger Fort Circuit", "Sawai Madhopur", ["Ranthambore", "Ranthambore safari", "Ranthambore Fort"], "tourism_circuits", "Ranthambore pairs a historic hill fort with a protected tiger-reserve landscape; safari zones and slots are independent from the fort visit.", _profile(["wildlife", "heritage", "photography"], 2880, "medium", "October–June is the broad safari season subject to park rules; heat and monsoon change comfort and access.", walking="medium", budget="high", notes="Book safari permits early and separate wildlife probability from heritage sightseeing.")),
    ("Gir Asiatic Lion Safari", "Sasan Gir", ["Gir National Park", "Asiatic lion"], "incredible_india", "Gir is the principal protected landscape associated with the Asiatic lion; safari access, zones, and seasonal closures are controlled by the forest department.", _profile(["wildlife", "nature", "photography"], 1440, "medium", "October–May is the usual safari window subject to official closures and heat.", walking="low", budget="high", notes="Use official permits and never promise lion sightings.")),
    ("Rann of Kutch Desert and Craft Circuit", "Kutch", ["Rann Utsav", "White Rann", "Kutch"], "tourism_circuits", "Kutch combines salt-desert landscapes, pastoral and artisan communities, coastal ecology, and seasonal festival infrastructure across a wide district.", _profile(["desert", "craft", "culture", "photography"], 4320, "medium", "November–February is the usual cool-season window; summer heat is severe and access rules are seasonal.", walking="medium", budget="mixed", notes="Treat villages and craft communities as living places; ask before photography and buying.")),
    ("Rock Shelters of Bhimbetka", "Bhopal", ["Bhimbetka", "prehistoric rock shelters"], "unesco_india", "Bhimbetka preserves prehistoric rock shelters and paintings in a sandstone landscape south of Bhopal, making it a dedicated archaeology-and-nature half-day rather than a city museum stop.", _profile(["archaeology", "nature", "photography"], 360, "medium", "October–March is generally more comfortable for the outdoor site.", walking="medium", notes="Wear suitable shoes; do not touch or apply anything to painted surfaces.")),
    ("Nalanda Mahavihara Archaeological Site", "Nalanda", ["Nalanda", "Nalanda University ruins"], "unesco_india", "Nalanda Mahavihara preserves the archaeological remains of a major Buddhist monastic and scholastic center in Bihar, best paired with Rajgir and Bodh Gaya over a multi-stop route.", _profile(["Buddhist heritage", "archaeology", "learning"], 360, "medium", "October–March is generally more comfortable for the open archaeological complex.", walking="medium", notes="Keep a full transfer buffer between Nalanda, Rajgir, and Bodh Gaya.")),
    ("Dholavira Harappan Archaeology", "Dholavira", ["Dholavira", "Harappan city Gujarat"], "unesco_india", "Dholavira is an excavated Harappan city on Khadir island in the Rann of Kutch, notable for urban planning, reservoirs, fortifications, and a remote desert setting.", _profile(["archaeology", "desert", "history"], 480, "medium", "November–February is generally the kinder outdoor window; summer heat and remote roads are demanding.", walking="medium", notes="Plan as a dedicated remote excursion with fuel, water, and route confirmation.")),
    ("Champaner Pavagadh Archaeology Circuit", "Champaner", ["Champaner-Pavagadh", "Pavagadh", "Kalika Mata hill"], "unesco_india", "Champaner-Pavagadh combines a historic fortified city, mosques, stepwells, temples, and a sacred hill landscape in Gujarat.", _profile(["heritage", "architecture", "spiritual", "walking"], 480, "high", "October–February is generally easier for the mixed-site outdoor circuit.", walking="high", notes="Separate the archaeological lower circuit from the hill pilgrimage logistics.")),
    ("Ramappa Temple Heritage Stop", "Palampet", ["Ramappa Temple", "Rudreshwara Temple"], "unesco_india", "Ramappa Temple is a 13th-century Kakatiya temple in Telangana known for its sculptural detail and lightweight brick superstructure, best treated as a dedicated heritage stop outside Hyderabad or Warangal.", _profile(["temple", "architecture", "history"], 240, "medium", "October–February is generally more comfortable for the site and nearby lake landscape.", walking="medium", notes="It is a transfer destination, not a quick Hyderabad neighborhood activity.")),
    ("Belur Halebidu Hoysala Circuit", "Belur", ["Hoysala temples", "Halebidu", "Sacred Ensembles of the Hoysalas"], "unesco_india", "Belur and Halebidu form a sculptural Hoysala temple circuit in Karnataka, with richly carved soapstone architecture spread across separate towns.", _profile(["temple", "architecture", "history", "photography"], 1440, "medium", "October–February is generally comfortable; temple worship and festival schedules vary.", walking="medium", notes="Allow road time between Belur and Halebidu and follow active-temple etiquette.")),
    ("Santiniketan Arts and Learning Circuit", "Santiniketan", ["Shantiniketan", "Visva-Bharati", "Tagore heritage"], "unesco_india", "Santiniketan is associated with Rabindranath Tagore's educational and artistic vision and a living cultural campus landscape in West Bengal.", _profile(["arts", "learning", "culture", "slow travel"], 480, "low", "October–March is generally more comfortable; campus and festival access can vary.", walking="medium", notes="Check campus access and event dates; respect active educational spaces.")),
    ("Charaideo Moidams Ahom Heritage", "Charaideo", ["Moidams", "Ahom burial mounds", "Sivasagar"], "unesco_india", "The Moidams of Charaideo are mound-burial monuments associated with the Ahom royal tradition in Assam, best combined with a wider upper-Assam heritage route.", _profile(["heritage", "archaeology", "culture"], 480, "medium", "October–April is generally more comfortable for the regional route; monsoon affects roads.", walking="medium", notes="Plan this as a regional circuit with Sivasagar rather than a short Guwahati excursion.")),
    ("Great Himalayan National Park Trek Base", "Kullu", ["GHNP", "Great Himalayan National Park"], "unesco_india", "The Great Himalayan National Park protects high-altitude Himalayan ecosystems and is a guided nature-and-trek destination where permits, seasons, and trail conditions matter.", _profile(["trekking", "wildlife", "mountains", "nature"], 4320, "high", "April–June and September–November are common planning windows; snow and monsoon alter trails.", walking="high", budget="high", notes="Use licensed local guides and verify permits, weather, and rescue access.")),
    ("Khangchendzonga Sacred Mountain Landscape", "Sikkim", ["Kangchenjunga", "Khangchendzonga National Park", "Sikkim trekking"], "unesco_india", "Khangchendzonga National Park is a mixed natural-and-cultural Himalayan landscape where sacred geography, biodiversity, and high-altitude access overlap.", _profile(["mountains", "culture", "nature", "trekking"], 4320, "high", "March–May and October–November are common clearer-season windows; permits and weather govern access.", walking="high", budget="high", notes="Do not treat high-altitude routes as casual sightseeing; confirm permits and acclimatisation.")),
]


# Normalized planning metadata. These records deliberately separate durable
# destination characteristics from fast-changing operational observations.
# Values are planning estimates and remain reviewable through the staff queue.
PROFILES = [
    ("Varanasi Ganga Ghats", "Uttar Pradesh", "North", "city", ["spiritual", "culture", "food", "photography"], ["October–March"], 2, 3, 80, "Varanasi", ["VNS"], "Airport and rail gateway; dense old-city lanes are mostly walk/boat based.", "Heat, crowds, steps, and river conditions require flexible days.", {"walking": "high", "wheelchair": "limited", "family": "medium"}, "incredible_india"),
    ("Rishikesh Ganga and Ashram Circuit", "Uttarakhand", "North", "foothills", ["spiritual", "wellness", "adventure", "nature"], ["October–April"], 2, 4, 372, "Dehradun", ["DED"], "Dehradun airport and Haridwar/Rishikesh rail-road gateways.", "Rafting, cliff edges, currents, and monsoon closures need operator checks.", {"walking": "medium", "wheelchair": "limited", "family": "medium"}, "tourism_circuits"),
    ("Golden Temple Langar Experience", "Punjab", "North", "city", ["spiritual", "community", "food", "culture"], ["October–March"], 1, 2, 218, "Amritsar", ["ATQ"], "Strong air and rail connectivity; old-city heritage is locally clustered.", "Follow worship etiquette, head covering, footwear, and crowd guidance.", {"walking": "medium", "wheelchair": "medium", "family": "high"}, "incredible_india"),
    ("Dal Lake and Srinagar Mughal Gardens", "Jammu and Kashmir", "North", "valley", ["nature", "photography", "heritage", "slow travel"], ["April–October"], 3, 5, 1585, "Srinagar", ["SXR"], "Srinagar airport and road gateway for Kashmir valley circuits.", "Verify current advisories, weather, road access, and licensed boat operators.", {"walking": "medium", "wheelchair": "limited", "family": "medium"}, "incredible_india"),
    ("Leh Ladakh Acclimatisation Base", "Ladakh", "North", "high_altitude", ["mountains", "culture", "road trip", "photography"], ["June–September"], 4, 8, 3500, "Leh", ["IXL"], "Fly to Leh or use seasonal mountain roads; acclimatisation day is mandatory.", "High-altitude illness, permits, cold, and road closures are material constraints.", {"walking": "high", "wheelchair": "limited", "family": "low"}, "incredible_india"),
    ("Goa Coastal and Heritage Circuit", "Goa", "West", "coastal", ["beach", "heritage", "food", "nightlife"], ["November–February"], 3, 6, 7, "Goa", ["GOI", "GOX"], "Two airports and rail gateways; select north, central, or south base.", "Sea conditions, heat, traffic, and nightlife safety need local judgment.", {"walking": "medium", "wheelchair": "medium", "family": "medium"}, "goa_official"),
    ("Kerala Backwaters Slow Travel", "Kerala", "South", "backwaters", ["slow travel", "nature", "food", "wellness"], ["October–March"], 2, 4, 1, "Kochi", ["COK"], "Kochi or Thiruvananthapuram gateways; waterways require licensed operators.", "Compare boat safety, waste handling, weather, and overnight route.", {"walking": "low", "wheelchair": "limited", "family": "high"}, "incredible_india"),
    ("Fort Kochi Heritage Walk", "Kerala", "South", "heritage_city", ["heritage", "food", "art", "walking"], ["October–March"], 1, 3, 5, "Kochi", ["COK"], "Airport, metro, rail, and ferry connections; compact local heritage area.", "Heat, rain, uneven surfaces, and active religious sites affect the walk.", {"walking": "high", "wheelchair": "medium", "family": "medium"}, "incredible_india"),
    ("Munnar Tea Hills", "Kerala", "South", "hill_station", ["nature", "tea", "mountains", "slow travel"], ["September–May"], 2, 4, 1532, "Kochi", ["COK"], "Road transfer from Kochi/Madurai; winding hill roads and dispersed sights.", "Monsoon landslides, road conditions, and protected-area openings vary.", {"walking": "medium", "wheelchair": "limited", "family": "medium"}, "incredible_india"),
    ("Mysuru Palace and Heritage Day", "Karnataka", "South", "heritage_city", ["heritage", "palace", "food", "family"], ["October–February"], 1, 3, 763, "Bengaluru", ["BLR"], "Bengaluru airport gateway with rail/road connection to Mysuru.", "Dasara creates exceptional demand; palace and event schedules change.", {"walking": "medium", "wheelchair": "medium", "family": "high"}, "incredible_india"),
    ("Pondicherry French Quarter and Aurobindo Heritage", "Puducherry", "South", "coastal_city", ["heritage", "food", "wellness", "coast"], ["October–March"], 2, 4, 3, "Chennai", ["MAA"], "Chennai airport/rail gateway; local heritage is walkable but Auroville is separate.", "Heat, traffic, and controlled access at some institutions require planning.", {"walking": "high", "wheelchair": "medium", "family": "medium"}, "incredible_india"),
    ("Andaman Marine and Cellular Jail Circuit", "Andaman and Nicobar Islands", "South", "island", ["beach", "history", "marine", "adventure"], ["October–May"], 4, 7, 16, "Port Blair", ["IXZ"], "Fly to Port Blair; island ferries and weather buffers are essential.", "Sea conditions, ferry cancellations, permits, and reef rules affect plans.", {"walking": "medium", "wheelchair": "limited", "family": "medium"}, "incredible_india"),
    ("Gangtok Sikkim Mountain Base", "Sikkim", "North East", "mountain_city", ["mountains", "culture", "nature", "food"], ["March–May", "October–November"], 3, 5, 1650, "Bagdogra", ["IXB"], "Bagdogra airport/NJP rail gateway with long mountain road transfer.", "Permits, monsoon landslides, snow, and road status govern excursions.", {"walking": "medium", "wheelchair": "limited", "family": "medium"}, "incredible_india"),
    ("Meghalaya Waterfall and Living Root Bridge Circuit", "Meghalaya", "North East", "nature_circuit", ["nature", "adventure", "villages", "photography"], ["October–April"], 4, 7, 1496, "Guwahati", ["GAU"], "Guwahati airport/rail gateway; long road transfers connect Khasi hills.", "Wet trails, steps, monsoon roads, and remote access require local guides.", {"walking": "high", "wheelchair": "limited", "family": "low"}, "incredible_india"),
    ("Kaziranga Rhino Safari", "Assam", "North East", "wildlife", ["wildlife", "nature", "photography"], ["November–April"], 2, 4, 80, "Guwahati", ["GAU"], "Guwahati gateway; park entry zones are dispersed and seasonal.", "Flooding, park notices, safari permits, and wildlife uncertainty apply.", {"walking": "low", "wheelchair": "limited", "family": "medium"}, "unesco_india"),
    ("Sundarbans Mangrove Expedition", "West Bengal", "East", "wildlife", ["wildlife", "nature", "boat", "photography"], ["November–February"], 3, 5, 5, "Kolkata", ["CCU"], "Kolkata gateway followed by road/boat logistics through registered operators.", "Tides, weather, forest permissions, and boat safety govern the route.", {"walking": "low", "wheelchair": "limited", "family": "low"}, "unesco_india"),
    ("Ranthambore Tiger Fort Circuit", "Rajasthan", "North", "wildlife", ["wildlife", "heritage", "photography"], ["October–June"], 2, 4, 230, "Jaipur", ["JAI"], "Jaipur or Delhi gateway; Sawai Madhopur is the local rail base.", "Safari zones and slots are separate from fort access; sightings are never guaranteed.", {"walking": "medium", "wheelchair": "limited", "family": "medium"}, "tourism_circuits"),
    ("Gir Asiatic Lion Safari", "Gujarat", "West", "wildlife", ["wildlife", "nature", "photography"], ["October–May"], 2, 3, 150, "Rajkot", ["RAJ"], "Rajkot/Ahmedabad gateways with road transfer to Sasan Gir.", "Forest closures, heat, safari zones, and wildlife uncertainty apply.", {"walking": "low", "wheelchair": "limited", "family": "medium"}, "incredible_india"),
    ("Rann of Kutch Desert and Craft Circuit", "Gujarat", "West", "desert", ["desert", "craft", "culture", "photography"], ["November–February"], 3, 5, 15, "Bhuj", ["BHJ"], "Bhuj is the practical gateway; villages and salt desert are widely dispersed.", "Severe summer heat, seasonal access rules, and respectful community visits matter.", {"walking": "medium", "wheelchair": "limited", "family": "medium"}, "tourism_circuits"),
    ("Rock Shelters of Bhimbetka", "Madhya Pradesh", "Central", "archaeology", ["archaeology", "nature", "photography"], ["October–March"], 1, 2, 621, "Bhopal", ["BHO"], "Bhopal airport/rail gateway with short road transfer.", "Uneven paths and conservation rules require suitable shoes and care.", {"walking": "medium", "wheelchair": "limited", "family": "medium"}, "unesco_india"),
    ("Nalanda Mahavihara Archaeological Site", "Bihar", "East", "archaeology", ["Buddhist heritage", "archaeology", "learning"], ["October–March"], 2, 3, 67, "Patna", ["PAT"], "Patna gateway; pair with Rajgir and Bodh Gaya as a Bihar circuit.", "Open-site heat and multi-stop road transfers require buffer.", {"walking": "medium", "wheelchair": "medium", "family": "medium"}, "unesco_india"),
    ("Dholavira Harappan Archaeology", "Gujarat", "West", "archaeology", ["archaeology", "desert", "history"], ["November–February"], 2, 3, 15, "Bhuj", ["BHJ"], "Remote road excursion from Bhuj with fuel, water, and route confirmation.", "Summer heat, sparse services, and remote-road conditions are material.", {"walking": "medium", "wheelchair": "limited", "family": "low"}, "unesco_india"),
    ("Champaner Pavagadh Archaeology Circuit", "Gujarat", "West", "heritage", ["heritage", "architecture", "spiritual", "walking"], ["October–February"], 1, 2, 800, "Vadodara", ["BDQ"], "Vadodara gateway with road transfer; lower ruins and sacred hill differ.", "Hill pilgrimage involves steep/uneven sections and crowd controls.", {"walking": "high", "wheelchair": "limited", "family": "medium"}, "unesco_india"),
    ("Ramappa Temple Heritage Stop", "Telangana", "South", "heritage", ["temple", "architecture", "history"], ["October–February"], 1, 2, 300, "Hyderabad", ["HYD"], "Hyderabad or Warangal gateway; dedicated road stop outside the cities.", "Road distance and active-temple etiquette need a slower plan.", {"walking": "medium", "wheelchair": "medium", "family": "medium"}, "unesco_india"),
    ("Belur Halebidu Hoysala Circuit", "Karnataka", "South", "heritage", ["temple", "architecture", "history", "photography"], ["October–February"], 2, 3, 960, "Bengaluru", ["BLR"], "Bengaluru/Mangaluru gateways; Belur and Halebidu are separate towns.", "Road time, temple worship, and uneven stone surfaces affect pacing.", {"walking": "medium", "wheelchair": "limited", "family": "medium"}, "unesco_india"),
    ("Santiniketan Arts and Learning Circuit", "West Bengal", "East", "culture", ["arts", "learning", "culture", "slow travel"], ["October–March"], 1, 2, 58, "Kolkata", ["CCU"], "Kolkata gateway with rail/road connection to Bolpur-Santiniketan.", "Campus and festival access varies; active educational spaces need respect.", {"walking": "medium", "wheelchair": "medium", "family": "medium"}, "unesco_india"),
    ("Charaideo Moidams Ahom Heritage", "Assam", "North East", "archaeology", ["heritage", "archaeology", "culture"], ["October–April"], 2, 4, 95, "Dibrugarh", ["DIB"], "Upper-Assam gateway; combine with Sivasagar as a regional route.", "Monsoon roads and dispersed sites require a regional rather than city-day plan.", {"walking": "medium", "wheelchair": "limited", "family": "medium"}, "unesco_india"),
    ("Great Himalayan National Park Trek Base", "Himachal Pradesh", "North", "wildlife", ["trekking", "wildlife", "mountains", "nature"], ["April–June", "September–November"], 4, 8, 1500, "Kullu", ["KUU"], "Kullu gateway; trekking zones require permits and local guide support.", "Trail conditions, altitude, weather, and rescue access must be checked.", {"walking": "high", "wheelchair": "limited", "family": "low"}, "unesco_india"),
    ("Khangchendzonga Sacred Mountain Landscape", "Sikkim", "North East", "high_altitude", ["mountains", "culture", "nature", "trekking"], ["March–May", "October–November"], 4, 8, 1780, "Gangtok", ["IXB"], "Gangtok/Pelling gateways; protected routes require permits and acclimatisation.", "High altitude, weather, remoteness, and sacred-landscape etiquette apply.", {"walking": "high", "wheelchair": "limited", "family": "low"}, "unesco_india"),
]


GATEWAY_ENTRIES = [
    ("Delhi Gateway", "Delhi", ["New Delhi", "Delhi airport", "Delhi tourism gateway"], "incredible_india", "city_guide", "National air and rail gateway for north-India heritage, Himalayan, Rajasthan, and Uttar Pradesh circuits."),
    ("Agra Gateway", "Agra", ["Agra", "Taj Mahal gateway"], "incredible_india", "city_guide", "Compact heritage gateway for the Taj Mahal, Agra Fort, and Braj/Golden Triangle extensions."),
    ("Jaipur Gateway", "Jaipur", ["Jaipur", "Pink City gateway"], "incredible_india", "city_guide", "Rajasthan gateway for Jaipur heritage, Ranthambore, Ajmer-Pushkar, and desert routes."),
    ("Mumbai Gateway", "Mumbai", ["Bombay", "Mumbai airport"], "incredible_india", "city_guide", "West-coast air and rail gateway for Maharashtra, Goa, Gujarat, and Konkan circuits."),
    ("Ahmedabad Gateway", "Ahmedabad", ["Ahmedabad airport", "Gujarat gateway"], "incredible_india", "city_guide", "Gujarat gateway for Ahmedabad heritage, Dwarka, Somnath, Kutch, and western India routes."),
    ("Kochi Gateway", "Kochi", ["Cochin", "Kerala gateway"], "incredible_india", "city_guide", "Kerala gateway for Fort Kochi, backwaters, Munnar, and southern hill/coastal routes."),
    ("Bengaluru Gateway", "Bengaluru", ["Bangalore", "Bengaluru airport"], "incredible_india", "city_guide", "South-India air gateway for Mysuru, Hoysala heritage, Tamil Nadu, and Karnataka circuits."),
    ("Kolkata Gateway", "Kolkata", ["Calcutta", "Kolkata airport"], "incredible_india", "city_guide", "East-India gateway for Bengal heritage, Sundarbans, Santiniketan, Odisha, and the North East."),
    ("Guwahati Gateway", "Guwahati", ["Gauhati", "Assam gateway"], "incredible_india", "city_guide", "North-East gateway for Assam, Meghalaya, Arunachal, Nagaland, and Sikkim road circuits."),
    ("Bhopal Gateway", "Bhopal", ["Bhopal airport", "Madhya Pradesh gateway"], "incredible_india", "city_guide", "Central-India gateway for Bhimbetka, Sanchi, Khajuraho, and wildlife routes."),
    ("Dehradun Gateway", "Dehradun", ["Dehradun airport", "Uttarakhand gateway"], "incredible_india", "city_guide", "Foothill gateway for Mussoorie, Auli, Rishikesh, and Garhwal mountain routes."),
    ("Bhubaneswar Gateway", "Bhubaneswar", ["Bhubaneswar airport", "Odisha gateway"], "incredible_india", "city_guide", "Odisha gateway for Bhubaneswar temples, Puri, Konark, Chilika, and eastern heritage routes."),
    ("Bhuj Gateway", "Bhuj", ["Kutch gateway", "Bhuj airport"], "incredible_india", "city_guide", "Kutch gateway for the Rann, craft villages, Dholavira, and western desert landscapes."),
]


ROUTES = [
    ("Delhi Gateway", "Agra Gateway", "road", 230, 210, 330, "Traffic and road conditions vary; use a generous transfer buffer.", "incredible_india"),
    ("Agra Gateway", "Jaipur Gateway", "road", 240, 240, 360, "Plan around monument timing and avoid stacking long transfer plus major sightseeing.", "tourism_circuits"),
    ("Mumbai Gateway", "Goa Coastal and Heritage Circuit", "air", 590, 75, 120, "Flight schedules and airport transfers vary; rail and road are slower alternatives.", "goa_official"),
    ("Kochi Gateway", "Munnar Tea Hills", "road", 130, 210, 300, "Winding hill road; rain can extend travel time.", "incredible_india"),
    ("Bengaluru Gateway", "Mysuru Palace and Heritage Day", "road", 145, 150, 240, "Weekend and festival traffic can materially extend the journey.", "incredible_india"),
    ("Kolkata Gateway", "Sundarbans Mangrove Expedition", "mixed", 110, 300, 480, "Road and boat legs are tide/operator dependent; overnight buffer is wise.", "unesco_india"),
    ("Guwahati Gateway", "Kaziranga Rhino Safari", "road", 220, 240, 360, "Park gate and safari zone determine the final transfer.", "unesco_india"),
    ("Bhopal Gateway", "Rock Shelters of Bhimbetka", "road", 45, 90, 150, "Short road transfer; open-site heat affects the best visit window.", "unesco_india"),
    ("Bhuj Gateway", "Dholavira Harappan Archaeology", "road", 250, 300, 420, "Remote road route; fuel, water, and route confirmation are required.", "unesco_india"),
    ("Jaipur Gateway", "Ranthambore Tiger Fort Circuit", "rail", 180, 180, 300, "Rail availability and last-mile transfer to the park need separate planning.", "tourism_circuits"),
]
