"""Citation-first India place corpus for Zenny's stable knowledge / agent memory.

Claims are short, sourced facts — not scraped articles. UNESCO World Heritage List
pages are the primary source for inscribed monuments. Official temple/tourism boards
are used only where a stable public URL exists. Run via ``python -m app.seed``.
"""

from datetime import date

CURATED_ON = date(2026, 8, 26)

# Approximate centroids for camera candidate narrowing only — not navigation pins.
LANDMARK_COORDINATES = {
    "Red Fort": (28.6562, 77.2410),
    "Humayun's Tomb": (28.5933, 77.2507),
    "Qutb Minar": (28.5244, 77.1855),
    "Taj Mahal": (27.1751, 78.0421),
    "Agra Fort": (27.1795, 78.0211),
    "Fatehpur Sikri": (27.0945, 77.6679),
    "Amber Fort": (26.9855, 75.8513),
    "Jantar Mantar, Jaipur": (26.9248, 75.8246),
    "Walled City of Jaipur": (26.9239, 75.8267),
    "Hawa Mahal": (26.9239, 75.8267),
    "City Palace, Jaipur": (26.9258, 75.8236),
    "Nahargarh Fort": (26.9373, 75.8155),
    "India Gate": (28.6129, 77.2295),
    "Lotus Temple": (28.5535, 77.2588),
    "Jama Masjid, Delhi": (28.6507, 77.2334),
    "Gateway of India": (18.9220, 72.8347),
    "Elephanta Caves": (18.9633, 72.9315),
    "Chhatrapati Shivaji Maharaj Terminus": (18.9400, 72.8355),
    "Ajanta Caves": (20.5519, 75.7033),
    "Ellora Caves": (20.0258, 75.1780),
    "Khajuraho Group of Monuments": (24.8318, 79.9199),
    "Group of Monuments at Hampi": (15.3350, 76.4600),
    "Sun Temple, Konark": (19.8876, 86.0945),
    "Group of Monuments at Mahabalipuram": (12.6169, 80.1997),
    "Great Living Chola Temples": (10.7828, 79.1318),
    "Buddhist Monuments at Sanchi": (23.4793, 77.7399),
    "Mahabodhi Temple Complex at Bodh Gaya": (24.6959, 84.9914),
    "Churches and Convents of Goa": (15.5009, 73.9116),
    "Jaisalmer Fort": (26.9124, 70.9126),
    "Chittorgarh Fort": (24.8880, 74.6450),
    "Kumbhalgarh Fort": (25.1483, 73.5805),
    "Rani-ki-Vav": (23.8588, 72.1016),
    "Historic City of Ahmadabad": (23.0225, 72.5714),
    "Golden Temple": (31.6200, 74.8765),
    "Mysore Palace": (12.3052, 76.6552),
    "Charminar": (17.3616, 78.4747),
    "Victoria Memorial": (22.5448, 88.3426),
    "Meenakshi Amman Temple": (9.9195, 78.1193),
    "Kashi Vishwanath Temple": (25.3109, 83.0107),
    "Sarnath": (25.3808, 83.0214),
    "Statue of Unity": (21.8380, 73.7191),
    "Capitol Complex, Chandigarh": (30.7589, 76.8070),
    "Kaziranga National Park": (26.5775, 93.1711),
    "Keoladeo National Park": (27.1591, 77.5217),
    "Mountain Railways of India": (27.0410, 88.2663),
}

SOURCES = {
    "red_fort": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/231", "official", "primary"),
    "humayun": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/232", "official", "primary"),
    "qutb": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/233", "official", "primary"),
    "agra_fort": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/251", "official", "primary"),
    "taj": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/252", "official", "primary"),
    "fatehpur": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/255", "official", "primary"),
    "hill_forts": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/247", "official", "primary"),
    "jantar": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/1338", "official", "primary"),
    "jaipur": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/1605", "official", "primary"),
    "ajanta": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/242", "official", "primary"),
    "ellora": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/243", "official", "primary"),
    "elephanta": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/244", "official", "primary"),
    "khajuraho": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/240", "official", "primary"),
    "hampi": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/241", "official", "primary"),
    "konark": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/246", "official", "primary"),
    "mahabalipuram": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/249", "official", "primary"),
    "chola": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/250", "official", "primary"),
    "sanchi": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/524", "official", "primary"),
    "mahabodhi": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/1056", "official", "primary"),
    "goa_churches": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/234", "official", "primary"),
    "rani_ki_vav": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/922", "official", "primary"),
    "cst": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/945", "official", "primary"),
    "mumbai_ensemble": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/1480", "official", "primary"),
    "ahmedabad": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/1551", "official", "primary"),
    "kaziranga": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/337", "official", "primary"),
    "keoladeo": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/340", "official", "primary"),
    "mountain_railways": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/944", "official", "primary"),
    "pattadakal": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/239", "official", "primary"),
    "chandigarh": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/1321", "official", "primary"),
    "nanda_devi": ("UNESCO World Heritage List", "https://whc.unesco.org/en/list/335", "official", "primary"),
    "asi": ("Archaeological Survey of India", "https://asi.nic.in/", "official", "primary"),
    "india_gate": ("National War Memorial / India Gate precinct, Government of India", "https://www.nationalwarmemorial.gov.in/", "official", "primary"),
    "lotus": ("Baha'i House of Worship, New Delhi", "https://www.bahaihouseofworship.in/", "official", "primary"),
    "sgpc": ("Shiromani Gurdwara Parbandhak Committee", "https://sgpc.net/", "official", "primary"),
    "mysore_palace": ("Mysore Palace Board", "https://mysorepalace.gov.in/", "official", "primary"),
    "statue_of_unity": ("Statue of Unity, Government of Gujarat", "https://www.statueofunity.in/", "official", "primary"),
    "kashi": ("Shri Kashi Vishwanath Temple", "https://shrikashivishwanath.org/", "official", "primary"),
    "tourism_india": ("Ministry of Tourism, Government of India", "https://tourism.gov.in/", "official", "primary"),
}

# Additional sourced claims attached to already-seeded corridor monuments.
# (name, city, aliases, source_key, claim, confidence)
DEEP_CORRIDOR_CLAIMS = [
    ("Taj Mahal", "Agra", ["Taj", "Rauza-i-Munawwara"], "taj",
     "UNESCO describes the Taj Mahal as an immense white-marble mausoleum built in Agra between 1631 and 1648 by order of Mughal emperor Shah Jahan in memory of his wife Mumtaz Mahal.",
     "verified"),
    ("Taj Mahal", "Agra", ["charbagh", "Taj garden"], "taj",
     "The mausoleum stands in a vast Mughal charbagh (four-part garden) aligned on the Yamuna, a layout UNESCO cites as part of the property's outstanding architectural composition.",
     "verified"),
    ("Taj Mahal", "Agra", ["Taj mosque", "jawab"], "taj",
     "Flanking the tomb are a mosque and a matching jawab (guest house) in red sandstone, creating the bilateral symmetry that UNESCO identifies as central to the ensemble.",
     "verified"),
    ("Taj Mahal", "Agra", ["pietra dura", "inlay"], "taj",
     "The white marble surfaces are decorated with pietra dura inlay of semi-precious stones in floral and calligraphic panels, a defining craft of the mausoleum.",
     "verified"),
    ("Taj Mahal", "Agra", ["Taj minarets"], "taj",
     "Four minarets frame the tomb chamber; they are slightly tilted outward, a construction choice often noted so that in a collapse they would fall away from the mausoleum.",
     "estimated"),
    ("Agra Fort", "Agra", ["Red Fort of Agra"], "agra_fort",
     "UNESCO records Agra Fort as a powerful 16th-century red-sandstone fortress whose 2.5 km circuit of walls encloses the imperial city of the Mughal rulers, near the Taj Mahal gardens.",
     "verified"),
    ("Agra Fort", "Agra", ["Diwan-i-Am Agra", "Hall of Public Audience Agra"], "agra_fort",
     "Within the fort, the Diwan-i-Am (Hall of Public Audience) is the ceremonial hall where the emperor received petitions — part of the palatial sequence inside the walls.",
     "verified"),
    ("Agra Fort", "Agra", ["Diwan-i-Khas Agra", "Hall of Private Audience Agra"], "agra_fort",
     "The Diwan-i-Khas (Hall of Private Audience) was reserved for receiving distinguished guests and conducting court in a more intimate palatial setting than the public hall.",
     "verified"),
    ("Agra Fort", "Agra", ["Musamman Burj", "Octagonal Tower"], "agra_fort",
     "Musamman Burj is an octagonal marble tower-palace overlooking the Yamuna; later Mughal tradition associates it with Shah Jahan's confinement with a view toward the Taj Mahal.",
     "estimated"),
    ("Agra Fort", "Agra", ["Jahangiri Mahal"], "agra_fort",
     "Jahangiri Mahal is a large palatial block inside Agra Fort associated with Akbar-period residential architecture in red sandstone, contrasting with later white-marble additions.",
     "verified"),
    ("Agra Fort", "Agra", ["Amar Singh Gate", "Delhi Gate Agra"], "agra_fort",
     "Historic gates including the Delhi Gate and Amar Singh Gate control entry through the fort's long circuit of walls.",
     "verified"),
    ("Red Fort", "Delhi", ["Lal Qila", "Lahori Gate"], "red_fort",
     "UNESCO identifies the Red Fort Complex as the palace fort of Shahjahanabad, Shah Jahan's 17th-century capital; the Lahori Gate is the principal public entrance used in the Independence Day flag hoisting.",
     "verified"),
    ("Red Fort", "Delhi", ["Diwan-i-Am Red Fort", "Naubat Khana"], "red_fort",
     "The processional axis from Lahori Gate passes the Naubat Khana (drum house) toward the Diwan-i-Am, the Hall of Public Audience of the Mughal court.",
     "verified"),
    ("Red Fort", "Delhi", ["Diwan-i-Khas Red Fort", "Rang Mahal"], "red_fort",
     "The inner palace sequence includes the Diwan-i-Khas, Rang Mahal, and other marble pavilions along the Yamuna-facing terrace of the imperial zenana and court.",
     "verified"),
    ("Red Fort", "Delhi", ["Moti Masjid Red Fort"], "red_fort",
     "The Moti Masjid (Pearl Mosque) is a later white-marble mosque added inside the fort complex for imperial private worship.",
     "verified"),
    ("Humayun's Tomb", "Delhi", ["garden-tomb", "charbagh Humayun"], "humayun",
     "UNESCO describes Humayun's Tomb as the first garden-tomb on the Indian subcontinent and a landmark in the development of Mughal architecture, set in a charbagh.",
     "verified"),
    ("Humayun's Tomb", "Delhi", ["double dome"], "humayun",
     "The mausoleum's high double dome and red sandstone with marble inlay established a prototype that later Mughal tombs, including the Taj Mahal, developed further.",
     "verified"),
    ("Qutb Minar", "Delhi", ["Qutub Minar", "Quwwat-ul-Islam", "Iron Pillar"], "qutb",
     "UNESCO lists Qutb Minar and its Monuments as a complex begun in the late 12th century, including the minaret, the Quwwat-ul-Islam mosque, and the Iron Pillar in the mosque courtyard.",
     "verified"),
    ("Qutb Minar", "Delhi", ["Alai Darwaza"], "qutb",
     "The Alai Darwaza is the southern gateway of the Quwwat-ul-Islam mosque, added under Alauddin Khalji, and is a key early example of true arcuate construction in the complex.",
     "verified"),
    ("Fatehpur Sikri", "Agra", ["Buland Darwaza", "Jama Masjid Fatehpur"], "fatehpur",
     "UNESCO notes Fatehpur Sikri was built in the second half of the 16th century by Akbar as a short-lived Mughal capital; the Jama Masjid and monumental Buland Darwaza dominate the sacred court.",
     "verified"),
    ("Fatehpur Sikri", "Agra", ["Panch Mahal", "Diwan-i-Khas Fatehpur", "Ankh Michauli"], "fatehpur",
     "The palatial zone includes distinctive structures such as the Panch Mahal and the Diwan-i-Khas, whose planning expresses Akbar-period court ceremonial and experimental architecture.",
     "verified"),
    ("Amber Fort", "Jaipur", ["Amer Fort", "Ganesh Pol", "Sheesh Mahal Amber"], "hill_forts",
     "Amber Fort is one of the Hill Forts of Rajasthan inscribed by UNESCO; its palaces are reached through ceremonial gates such as Ganesh Pol, with mirrored Sheesh Mahal interiors in the upper palace.",
     "verified"),
    ("Amber Fort", "Jaipur", ["Suraj Pol", "Diwan-i-Am Amber"], "hill_forts",
     "The fort's processional courts include Suraj Pol and a Diwan-i-Am, organizing Rajput-Mughal court life on the hill above Maota Lake.",
     "verified"),
    ("Jantar Mantar, Jaipur", "Jaipur", ["Samrat Yantra", "Jai Prakash Yantra"], "jantar",
     "UNESCO describes the Jaipur Jantar Mantar as an 18th-century astronomical observation site built by Sawai Jai Singh II, with monumental masonry instruments including the Samrat Yantra.",
     "verified"),
    ("Walled City of Jaipur", "Jaipur", ["Pink City", "Sawai Jai Singh II"], "jaipur",
     "UNESCO records that Jaipur was founded in 1727 by Sawai Jai Singh II as a planned trade-capital with a grid of streets, public squares, and bazaars, inscribed in 2019.",
     "verified"),
    ("Hawa Mahal", "Jaipur", ["Palace of Winds"], "jaipur",
     "Hawa Mahal stands on the edge of Jaipur's walled city bazaar street as a five-storey facade of screened windows, built so royal women could observe street life while remaining unseen.",
     "estimated"),
    ("City Palace, Jaipur", "Jaipur", ["Chandra Mahal", "Mubarak Mahal"], "jaipur",
     "The City Palace complex occupies the heart of the 1727 planned city and remains associated with the Kachwaha court, combining Chandra Mahal residences with later museum courts.",
     "estimated"),
    ("Nahargarh Fort", "Jaipur", ["Tiger Fort"], "hill_forts",
     "Nahargarh is one of the forts overlooking the walled city of Jaipur, forming part of the same hill-fort landscape as Amber in the UNESCO Hill Forts of Rajasthan series context for the region.",
     "estimated"),
]

# India's most-visited / globally significant places beyond the starter corridor.
# entity_type monument = itinerary-eligible; monument_feature is excluded from itineraries.
INDIA_PLACES = [
    ("India Gate", "Delhi", ["All India War Memorial"], "india_gate", "monument",
     "India Gate is the All India War Memorial arch on Rajpath (Kartavya Path) in New Delhi, commemorating soldiers who died in the First World War and the Third Anglo-Afghan War."),
    ("Lotus Temple", "Delhi", ["Baha'i House of Worship Delhi"], "lotus", "monument",
     "The Lotus Temple is the Baha'i House of Worship in New Delhi, a lotus-shaped concrete temple open to people of all religions for silent prayer and meditation."),
    ("Jama Masjid, Delhi", "Delhi", ["Masjid-i-Jahan-Numa"], "tourism_india", "monument",
     "Jama Masjid in Shahjahanabad is among India's largest congregational mosques, commissioned by Shah Jahan and sited beside the Red Fort's old city."),
    ("Gateway of India", "Mumbai", ["Apollo Bunder"], "tourism_india", "monument",
     "The Gateway of India on Mumbai Harbour is a 20th-century basalt arch built to commemorate the 1911 visit of King George V and Queen Mary, and later became the ceremonial harbour landmark of Bombay."),
    ("Elephanta Caves", "Mumbai", ["Gharapuri"], "elephanta", "monument",
     "UNESCO lists the Elephanta Caves as a rock-cut temple complex on an island in Mumbai Harbour, famous for the colossal Trimurti sculpture of Shiva."),
    ("Chhatrapati Shivaji Maharaj Terminus", "Mumbai", ["CST", "Victoria Terminus", "VT"], "cst", "monument",
     "UNESCO describes Chhatrapati Shivaji Terminus (formerly Victoria Terminus) as an outstanding example of Victorian Gothic Revival architecture in India, still a working railway terminus."),
    ("Ajanta Caves", "Aurangabad", ["Ajanta"], "ajanta", "monument",
     "UNESCO lists the Ajanta Caves as Buddhist rock-cut cave monuments in Maharashtra whose paintings and sculptures are masterpieces of Buddhist religious art from roughly the 2nd century BCE to the 6th century CE."),
    ("Ellora Caves", "Aurangabad", ["Kailasa Temple", "Kailasanatha"], "ellora", "monument",
     "UNESCO lists Ellora as a sequence of 34 monasteries and temples cut into basalt, including the monolithic Kailasa temple, illustrating Buddhist, Hindu, and Jain faith side by side."),
    ("Khajuraho Group of Monuments", "Khajuraho", ["Khajuraho temples"], "khajuraho", "monument",
     "UNESCO lists the Khajuraho Group of Monuments as a surviving cluster of Chandela-period Hindu and Jain temples in Madhya Pradesh, known for Nagara architecture and sculptural programmes."),
    ("Group of Monuments at Hampi", "Hampi", ["Vijayanagara", "Virupaksha Temple"], "hampi", "monument",
     "UNESCO lists Hampi as the ruined capital of the Vijayanagara Empire, with temple, palace, and fort remains along the Tungabhadra, including the Virupaksha temple still in worship."),
    ("Sun Temple, Konark", "Konark", ["Konarak", "Black Pagoda"], "konark", "monument",
     "UNESCO lists the Sun Temple at Konark as a 13th-century Kalinga temple conceived as a colossal chariot of the sun god Surya, with 24 carved wheels and pulling horses."),
    ("Group of Monuments at Mahabalipuram", "Mahabalipuram", ["Mamallapuram", "Shore Temple"], "mahabalipuram", "monument",
     "UNESCO lists Mahabalipuram as a group of 7th–8th century Pallava rock-cut rathas, cave temples, sculpted reliefs, and the Shore Temple on the Tamil Nadu coast."),
    ("Great Living Chola Temples", "Thanjavur", ["Brihadisvara", "Brihadeeswara", "Rajarajesvaram"], "chola", "monument",
     "UNESCO's Great Living Chola Temples include the Brihadisvara Temple at Thanjavur, a living 11th-century Chola imperial temple of granite with a towering vimana."),
    ("Buddhist Monuments at Sanchi", "Sanchi", ["Sanchi Stupa", "Great Stupa"], "sanchi", "monument",
     "UNESCO lists Sanchi as the oldest Buddhist sanctuary in existence, developed from the 3rd century BCE, whose Great Stupa and gateways are among India's finest early Buddhist art."),
    ("Mahabodhi Temple Complex at Bodh Gaya", "Bodh Gaya", ["Bodhgaya", "Bodhi Tree temple"], "mahabodhi", "monument",
     "UNESCO lists the Mahabodhi Temple Complex as one of the four holy sites related to the life of the Buddha, marking the place of Enlightenment, with the present temple dating mainly from the 5th–6th centuries."),
    ("Churches and Convents of Goa", "Old Goa", ["Basilica of Bom Jesus", "Se Cathedral"], "goa_churches", "monument",
     "UNESCO lists the Churches and Convents of Goa as the former capital of the Portuguese Indies, including the Basilica of Bom Jesus which houses the relics of St Francis Xavier."),
    ("Jaisalmer Fort", "Jaisalmer", ["Sonar Quila", "Golden Fort"], "hill_forts", "monument",
     "Jaisalmer Fort is one of the six Hill Forts of Rajasthan on the UNESCO list: a living sandstone fort-city in the Thar Desert with palaces, Jain temples, and merchants' havelis inside the walls."),
    ("Chittorgarh Fort", "Chittorgarh", ["Chittor Fort"], "hill_forts", "monument",
     "Chittorgarh Fort is the largest in the UNESCO Hill Forts of Rajasthan series, a vast plateau fortress of the Sisodia Rajputs with towers, palaces, and water bodies."),
    ("Kumbhalgarh Fort", "Kumbhalgarh", ["Kumbhalgarh wall"], "hill_forts", "monument",
     "Kumbhalgarh is a UNESCO Hill Fort of Rajasthan whose perimeter walls run for tens of kilometres across the Aravalli hills, enclosing palaces and temples."),
    ("Rani-ki-Vav", "Patan", ["Queen's Stepwell"], "rani_ki_vav", "monument",
     "UNESCO lists Rani-ki-Vav at Patan, Gujarat, as an 11th-century inverted-temple stepwell built in the Maru-Gurjara style, with sculptural levels dedicated primarily to Vishnu."),
    ("Historic City of Ahmadabad", "Ahmedabad", ["Ahmedabad old city", "Bhadra"], "ahmedabad", "monument",
     "UNESCO lists the Historic City of Ahmadabad as a walled historic capital founded in the 15th century, with a dense fabric of wooden houses, pols, mosques, and tombs."),
    ("Golden Temple", "Amritsar", ["Harmandir Sahib", "Sri Darbar Sahib"], "sgpc", "monument",
     "Harmandir Sahib, the Golden Temple in Amritsar, is the principal gurdwara of Sikhism, set in the Amrit Sarovar, administered by the Shiromani Gurdwara Parbandhak Committee, and open to all."),
    ("Mysore Palace", "Mysuru", ["Amba Vilas", "Mysuru Palace"], "mysore_palace", "monument",
     "Mysore Palace (Amba Vilas) is the official seat of the Wadiyars and a major Indo-Saracenic palace complex whose illuminated Dasara season is one of Karnataka's principal visitor events."),
    ("Charminar", "Hyderabad", ["Four Minarets"], "tourism_india", "monument",
     "Charminar is the 1591 ceremonial monument and mosque at the centre of Hyderabad's old city, built by Muhammad Quli Qutb Shah, with four grand arches facing the cardinal bazaars."),
    ("Victoria Memorial", "Kolkata", ["Victoria Memorial Hall"], "tourism_india", "monument",
     "The Victoria Memorial in Kolkata is a white-marble museum-memorial completed in the early 20th century in memory of Queen Victoria, now a national museum of the city and the Raj period."),
    ("Meenakshi Amman Temple", "Madurai", ["Meenakshi Temple", "Madurai Meenakshi"], "tourism_india", "monument",
     "Meenakshi Amman Temple in Madurai is a living Dravidian temple complex dedicated to Meenakshi and Sundareswarar, famed for its towering painted gopurams on the Vaigai river city."),
    ("Kashi Vishwanath Temple", "Varanasi", ["Golden Temple Varanasi", "Jyotirlinga Kashi"], "kashi", "monument",
     "Shri Kashi Vishwanath is a principal Jyotirlinga temple of Shiva on the Ganga in Varanasi, one of Hinduism's holiest tirthas, with the present shrine rebuilt in the 18th century and a major visitor corridor beside the river."),
    ("Sarnath", "Varanasi", ["Deer Park", "Dhamek Stupa"], "asi", "monument",
     "Sarnath, north of Varanasi, is the site of the Buddha's first sermon; the Archaeological Survey of India protects the Dhamek Stupa, monasteries, and the museum that holds the Lion Capital of Ashoka."),
    ("Statue of Unity", "Kevadia", ["Sardar Patel statue"], "statue_of_unity", "monument",
     "The Statue of Unity on the Narmada in Gujarat is a colossal statue of Sardar Vallabhbhai Patel developed as a national memorial and visitor destination by the Government of Gujarat."),
    ("Capitol Complex, Chandigarh", "Chandigarh", ["Le Corbusier Chandigarh", "Open Hand"], "chandigarh", "monument",
     "UNESCO includes Chandigarh's Capitol Complex among the Architectural Work of Le Corbusier, an outstanding contribution to the Modern Movement, with the Secretariat, Assembly, and High Court."),
    ("Kaziranga National Park", "Kaziranga", ["one-horned rhinoceros"], "kaziranga", "place",
     "UNESCO lists Kaziranga in Assam as a natural World Heritage site on the Brahmaputra floodplain, the world's major habitat of the greater one-horned rhinoceros."),
    ("Keoladeo National Park", "Bharatpur", ["Bharatpur Bird Sanctuary"], "keoladeo", "place",
     "UNESCO lists Keoladeo (Bharatpur) as a man-made wetland World Heritage site and a major wintering ground for migratory waterfowl, including (historically) the Siberian crane."),
    ("Mountain Railways of India", "Darjeeling", ["Darjeeling Himalayan Railway", "toy train"], "mountain_railways", "place",
     "UNESCO lists the Mountain Railways of India, including the Darjeeling Himalayan Railway, as outstanding examples of hill railway engineering from the British colonial period that are still in use."),
    ("Group of Monuments at Pattadakal", "Pattadakal", ["Pattadakal"], "pattadakal", "monument",
     "UNESCO lists Pattadakal in Karnataka as a 7th–8th century Chalukya sacred ensemble on the Malaprabha, blending northern and southern Indian temple forms."),
    ("Nanda Devi and Valley of Flowers National Parks", "Chamoli", ["Valley of Flowers", "Nanda Devi"], "nanda_devi", "place",
     "UNESCO lists Nanda Devi and Valley of Flowers National Parks in Uttarakhand as a high-Himalayan wilderness of outstanding alpine flora and the Nanda Devi basin."),
]

MONUMENT_FEATURES = [
    ("Taj Mahal — Main Mausoleum", "Agra", ["tomb chamber", "cenotaphs"], "taj",
     "The central onion dome covers an octagonal tomb chamber that holds cenotaphs of Mumtaz Mahal and Shah Jahan; the actual graves lie in a lower crypt, a typical Mughal arrangement."),
    ("Taj Mahal — Great Gate", "Agra", ["Darwaza-i-Rauza", "Taj gateway"], "taj",
     "The red-sandstone Great Gate (Darwaza-i-Rauza) frames the first axial view of the white mausoleum across the charbagh and is itself inlaid with verses and floral decoration."),
    ("Agra Fort — Diwan-i-Khas", "Agra", ["Hall of Private Audience"], "agra_fort",
     "Agra Fort's Diwan-i-Khas is the marble private-audience hall on the river terrace, used for receiving nobles rather than the general public of the Diwan-i-Am."),
    ("Red Fort — Lahori Gate", "Delhi", ["Lahori Gate"], "red_fort",
     "Lahori Gate is the main western entrance of the Red Fort, opening toward the old city's Chandni Chowk axis and used for the annual Independence Day ceremony."),
    ("Qutb Minar — Iron Pillar", "Delhi", ["Iron Pillar of Delhi"], "qutb",
     "The Iron Pillar in the Qutb mosque courtyard is a 4th-century inscribed metallurgical pillar, famous for its rust-resistant composition, standing among later Sultanate structures."),
    ("Amber Fort — Sheesh Mahal", "Jaipur", ["Mirror Palace Amber"], "hill_forts",
     "The Sheesh Mahal at Amber is a mirrored palace chamber whose glass inlay was designed to multiply lamplight, part of the upper palace apartments of the Kachwaha court."),
    ("Ellora Caves — Kailasa Temple", "Aurangabad", ["Cave 16 Ellora"], "ellora",
     "Ellora Cave 16, the Kailasa temple, is a monolithic excavation representing Mount Kailasa, carved downward from a single basalt outcrop — the largest of the Ellora monuments."),
    ("Hampi — Virupaksha Temple", "Hampi", ["Virupaksha"], "hampi",
     "The Virupaksha Temple at Hampi is a living shrine of the Vijayanagara sacred centre, predating and outlasting the 14th–16th century imperial capital around it."),
    ("Mahabalipuram — Shore Temple", "Mahabalipuram", ["Shore Temple"], "mahabalipuram",
     "The Shore Temple is a structural stone temple on the Bay of Bengal, part of the Pallava group, dedicated primarily to Shiva and unusual as a surviving seaside Pallava sanctuary."),
    ("Konark — Chariot Wheels", "Konark", ["Konark wheels"], "konark",
     "The Sun Temple is planned as Surya's chariot: twelve pairs of richly carved stone wheels along the platform are both symbolic calendar forms and structural ornament of the Kalinga vimana."),
    ("Ajanta Caves — Paintings", "Aurangabad", ["Ajanta murals", "Cave 1 Ajanta"], "ajanta",
     "Ajanta's later caves preserve Buddhist wall paintings of Jataka stories and courtly scenes; UNESCO cites the paintings and sculptures as masterpieces of Buddhist religious art."),
    ("Sanchi — Great Stupa gateways", "Sanchi", ["Sanchi torana", "toranas"], "sanchi",
     "The Great Stupa at Sanchi is ringed by carved stone torana gateways whose reliefs narrate Buddhist stories; UNESCO identifies the sanctuary as developed from the 3rd century BCE."),
    ("Brihadisvara — Vimana", "Thanjavur", ["Thanjavur vimana", "Rajarajesvaram tower"], "chola",
     "The Brihadisvara Temple's granite vimana is the vertical marker of the Chola imperial temple at Thanjavur, part of UNESCO's Great Living Chola Temples."),
    ("Mahabalipuram — Arjuna's Penance", "Mahabalipuram", ["Descent of the Ganges", "Bhagiratha relief"], "mahabalipuram",
     "The open-air rock relief often called Arjuna's Penance or the Descent of the Ganges is a Pallava narrative sculpture on the Mahabalipuram hill, part of the UNESCO group."),
    ("CST — Victorian Gothic terminus", "Mumbai", ["Victoria Terminus architecture"], "cst",
     "Chhatrapati Shivaji Maharaj Terminus combines Victorian Gothic Revival with Indian architectural motifs and remains a working railway terminus, as UNESCO records."),
    ("Meenakshi — Gopurams", "Madurai", ["Madurai gopuram", "Meenakshi towers"], "tourism_india",
     "Meenakshi Amman Temple is entered through soaring painted gopurams that mark the living temple-city of Madurai; it is a worship site with dress and photography rules, not a museum-only ruin."),
    ("Humayun's Tomb — Garden charbagh", "Delhi", ["Humayun charbagh", "Sunder Nursery neighbour"], "humayun",
     "Humayun's Tomb sits in a four-part Mughal garden (charbagh); UNESCO cites it as the first garden-tomb on the subcontinent, a prototype later developed at the Taj Mahal."),
    ("Fatehpur Sikri — Buland Darwaza", "Agra", ["Buland Darwaza"], "fatehpur",
     "The Buland Darwaza is the monumental victory gate of Fatehpur Sikri's Jama Masjid court, among the largest gateway structures of Mughal India."),
    ("Red Fort — Diwan-i-Khas", "Delhi", ["Hall of Private Audience Red Fort"], "red_fort",
     "The Red Fort's Diwan-i-Khas is the marble private-audience hall on the river terrace of Shahjahanabad's palace, distinct from the public Diwan-i-Am along the same processional axis."),
    ("Golden Temple — Amrit Sarovar", "Amritsar", ["sarovar", "holy tank Amritsar"], "sgpc",
     "Harmandir Sahib stands in the Amrit Sarovar, the sacred tank that gives Amritsar its name; circumambulation of the marble parikrama is part of the gurdwara visit, with head covering required."),
    ("Jaisalmer Fort — living streets", "Jaisalmer", ["Sonar Quila lanes"], "hill_forts",
     "Jaisalmer Fort is a living fort-city: palaces, Jain temples, and residential lanes sit inside the UNESCO Hill Forts of Rajasthan property, not an empty citadel."),
    ("Hampi — Vittala Temple", "Hampi", ["Stone Chariot", "Vittala"], "hampi",
     "The Vittala Temple complex at Hampi includes the iconic stone chariot and colonnaded halls on the Tungabhadra floodplain, a highlight of the Vijayanagara sacred centre."),
    ("Elephanta — Trimurti", "Mumbai", ["Maheshmurti", "Trimurti Elephanta"], "elephanta",
     "The colossal Trimurti (Maheshmurti) of Shiva is the principal sculpture of the Elephanta cave temple, reached by ferry from the Gateway of India when the harbour service runs."),
    ("Khajuraho — Kandariya Mahadeva", "Khajuraho", ["Kandariya"], "khajuraho",
     "Kandariya Mahadeva is the largest surviving Chandela temple in the Khajuraho western group, a Nagara shikhara densely carved with sculptural bands."),
    ("Goa — Basilica of Bom Jesus", "Old Goa", ["Bom Jesus relics"], "goa_churches",
     "The Basilica of Bom Jesus in Old Goa holds the relics of St Francis Xavier and is the best-known church of the UNESCO Churches and Convents of Goa ensemble."),
    ("Amber Fort — Ganesh Pol", "Jaipur", ["Ganesh Gate Amber", "Ganesh Pol"], "hill_forts",
     "Ganesh Pol is a ceremonial painted gateway on Amber Fort's processional climb into the palace courts, part of the UNESCO Hill Forts of Rajasthan palace-fort sequence."),
    ("Agra Fort — Diwan-i-Am", "Agra", ["Hall of Public Audience Agra Fort"], "agra_fort",
     "Agra Fort's Diwan-i-Am is the public audience hall where the emperor received petitions, distinct from the marble Diwan-i-Khas on the river terrace."),
    ("Agra Fort — Musamman Burj", "Agra", ["Octagonal Tower Agra", "Shah Jahan tower"], "agra_fort",
     "Musamman Burj is the octagonal marble tower-palace on Agra Fort's Yamuna face; later tradition links it with Shah Jahan's confinement and a view toward the Taj Mahal."),
    ("Agra Fort — Jahangiri Mahal", "Agra", ["Jahangiri Mahal rooms"], "agra_fort",
     "Jahangiri Mahal is a large Akbar-period red-sandstone palace block inside Agra Fort, contrasting with later white-marble pavilions on the river side."),
    ("Red Fort — Naubat Khana", "Delhi", ["Naqqar Khana", "drum house Red Fort"], "red_fort",
     "The Naubat Khana (drum house) stands on the Red Fort's processional path from Lahori Gate toward the Diwan-i-Am, where ceremonial music announced court arrivals."),
    ("Red Fort — Moti Masjid", "Delhi", ["Pearl Mosque Red Fort"], "red_fort",
     "The Moti Masjid is a compact white-marble mosque added inside the Red Fort for imperial private worship, set apart from the public Jama Masjid of Shahjahanabad."),
    ("Fatehpur Sikri — Panch Mahal", "Agra", ["Panch Mahal"], "fatehpur",
     "The Panch Mahal is a five-storey pillared palace pavilion in Fatehpur Sikri's court zone, an Akbar-period experimental structure open to the air."),
    ("Fatehpur Sikri — Diwan-i-Khas", "Agra", ["Diwan-i-Khas Fatehpur", "Ibadat Khana pillar"], "fatehpur",
     "Fatehpur Sikri's Diwan-i-Khas is a square hall with a central pillar and bridging galleries, associated with Akbar-period court discussion — a different building from Agra Fort's marble Diwan-i-Khas."),
    ("Qutb — Alai Darwaza", "Delhi", ["Alai Gate"], "qutb",
     "The Alai Darwaza is the southern sandstone-and-marble gateway of the Quwwat-ul-Islam mosque at the Qutb, added under Alauddin Khalji."),
    ("Humayun's Tomb — West Gate", "Delhi", ["Humayun gateway"], "humayun",
     "Humayun's Tomb is entered through a monumental west gate into the charbagh; the high double dome of the mausoleum is the visual centre of the garden-tomb."),
    ("Jantar Mantar — Samrat Yantra", "Jaipur", ["Samrat Yantra Jaipur"], "jantar",
     "The Samrat Yantra at Jaipur's Jantar Mantar is the site's largest masonry sundial, one of the monumental astronomical instruments built by Sawai Jai Singh II."),
    ("Hawa Mahal — screened facade", "Jaipur", ["Palace of Winds windows"], "jaipur",
     "Hawa Mahal's five-storey facade is a screen of small windows on the bazaar street, built so royal women could watch the city while remaining unseen."),
    ("City Palace Jaipur — Chandra Mahal", "Jaipur", ["Chandra Mahal"], "jaipur",
     "Chandra Mahal is the principal residential palace tower of Jaipur's City Palace complex at the heart of the 1727 planned city."),
    ("Konark — Audience Hall", "Konark", ["Jagamohana Konark"], "konark",
     "The surviving mass of Konark Sun Temple includes the jagamohana (audience hall) of the chariot-temple; the towering sikhara over the sanctum is largely lost."),
    ("Mahabalipuram — Five Rathas", "Mahabalipuram", ["Pancha Rathas", "Five Rathas"], "mahabalipuram",
     "The Five Rathas (Pancha Rathas) are Pallava monolithic rock-cut shrines south of the Shore Temple, part of the UNESCO Mahabalipuram group, carved from single granite outcrops."),
    ("Sanchi — Great Stupa", "Sanchi", ["Stupa 1 Sanchi"], "sanchi",
     "Sanchi Stupa 1, the Great Stupa, is the hemispherical Buddhist monument at the centre of the UNESCO sanctuary, developed from the Mauryan period with later gateways."),
    ("Mahabodhi — Bodhi Tree shrine", "Bodh Gaya", ["Bodhi Tree", "vajrasana"], "mahabodhi",
     "The Mahabodhi complex marks the place of the Buddha's Enlightenment; the Bodhi Tree and stone vajrasana sit beside the towering brick temple that UNESCO lists."),
    ("Rani-ki-Vav — sculpted levels", "Patan", ["stepwell galleries"], "rani_ki_vav",
     "Rani-ki-Vav is an inverted-temple stepwell whose descending levels are lined with sculptural panels, primarily Vaishnava, in the Maru-Gurjara style."),
    ("Chittorgarh — Vijay Stambha", "Chittorgarh", ["Tower of Victory Chittor"], "hill_forts",
     "The Vijay Stambha (Tower of Victory) is a carved stone tower inside Chittorgarh Fort, a landmark of the Sisodia citadel on the UNESCO Hill Forts of Rajasthan list."),
    ("Kumbhalgarh — perimeter wall", "Kumbhalgarh", ["Kumbhalgarh walls"], "hill_forts",
     "Kumbhalgarh's fortification walls run for tens of kilometres across the Aravallis, enclosing palaces and temples — the defensive landscape of this UNESCO hill fort."),
    ("Taj Mahal — Mosque and Jawab", "Agra", ["Taj mosque hall", "jawab pavilion"], "taj",
     "The Taj ensemble's red-sandstone mosque and matching jawab (guest house) flank the white mausoleum, creating the bilateral symmetry UNESCO identifies in the garden-tomb."),
    ("Fatehpur Sikri — Jodha Bai Palace", "Agra", ["Jodha Bai ka Mahal", "Shabistan-i-Iqbal"], "fatehpur",
     "The large palatial zenana block at Fatehpur Sikri commonly called Jodha Bai's Palace is a self-contained residential court of Akbar-period red sandstone."),
    ("Qutb — Tomb of Iltutmish", "Delhi", ["Iltutmish tomb"], "qutb",
     "The tomb of Iltutmish at the Qutb is a square chamber of carved red sandstone added beside the Quwwat-ul-Islam mosque, an early Sultanate funerary hall."),
    ("Humayun's Tomb — Barber's Tomb", "Delhi", ["Nai ka Gumbad"], "humayun",
     "The so-called Barber's Tomb (Nai ka Gumbad) is a smaller mausoleum in Humayun's garden-tomb precinct, a quieter satellite dome in the same charbagh landscape."),
    ("Ellora — Cave 10 chaitya", "Aurangabad", ["Vishvakarma cave", "Cave 10"], "ellora",
     "Ellora Cave 10, the Vishvakarma chaitya, is a rock-cut Buddhist worship hall with a stupa and ribbed ceiling, distinct from the Hindu Kailasa (Cave 16)."),
    ("Ajanta — Cave 26 chaitya", "Aurangabad", ["Ajanta Cave 26"], "ajanta",
     "Ajanta Cave 26 is a later Mahayana chaitya hall with a carved stupa and extensive sculpture, part of the painted-and-cut Buddhist gorge UNESCO lists."),
    ("Mahabalipuram — Mahishasuramardini cave", "Mahabalipuram", ["Mahishasuramardini mandapa"], "mahabalipuram",
     "The Mahishasuramardini cave-temple on Mahabalipuram hill contains Pallava reliefs of Durga's battle and Vishnu reclining, part of the UNESCO group above the Shore Temple."),
    ("Pattadakal — Virupaksha Temple", "Pattadakal", ["Pattadakal Virupaksha"], "pattadakal",
     "The Virupaksha Temple at Pattadakal is a major Early Chalukya structural temple on the Malaprabha, blending southern and northern forms in the UNESCO ensemble."),
    ("Golconda — Fateh Darwaza", "Hyderabad", ["Fateh Gate Golconda"], "asi",
     "Fateh Darwaza is a principal gateway of Golconda Fort, associated with the citadel's famous acoustic-clap demonstration along the entry path."),
    ("Charminar — four arches", "Hyderabad", ["Charminar mosque level"], "tourism_india",
     "Charminar's four grand arches open onto the cardinal bazaars of Hyderabad's old city; an upper mosque level sits over the ceremonial monument of 1591."),
    ("Mehrangarh — palatial apartments", "Jodhpur", ["Mehrangarh palaces", "Moti Mahal Jodhpur"], "tourism_india",
     "Mehrangarh's inner palatial apartments (including halls such as Moti Mahal) are museum rooms inside the cliff fort above Jodhpur's blue town."),
    ("Jaisalmer — palace square", "Jaisalmer", ["Jaisalmer Palace", "Fort palace"], "hill_forts",
     "The palace cluster at the crest of Jaisalmer Fort looks over the living fort-city lanes; it is part of the UNESCO Hill Forts of Rajasthan property, still inhabited below."),
    ("Gateway of India — arch", "Mumbai", ["Apollo Bunder arch"], "tourism_india",
     "The Gateway of India's basalt arch on Apollo Bunder is the harbour ceremonial front and the Elephanta ferry dock, a 20th-century Indo-Saracenic monument."),
    ("Lotus Temple — prayer hall", "Delhi", ["Lotus interior"], "lotus",
     "The Lotus Temple's interior is a silent Baháʼí prayer hall under the lotus-form concrete shells, open to all with posted quiet-and-photography rules."),
    ("Capitol Complex — Open Hand", "Chandigarh", ["Open Hand Monument"], "chandigarh",
     "The Open Hand Monument is the emblematic sculpture of Chandigarh's Capitol Complex, part of the UNESCO-listed Le Corbusier ensemble with the Assembly and High Court."),
    ("Taj Mahal — Pietra dura panels", "Agra", ["pietra dura Taj rooms"], "taj",
     "Inside and on the Taj mausoleum, floral pietra dura inlay of semi-precious stones covers the marble dados and cenotaph screens — the craft UNESCO associates with the tomb's decoration."),
    ("Amber Fort — Diwan-i-Am court", "Jaipur", ["Amber public audience"], "hill_forts",
     "Amber Fort's Diwan-i-Am sits in the processional courts above Suraj Pol, organising Rajput-Mughal public audience on the hill over Maota Lake."),
    ("Red Fort — Rang Mahal", "Delhi", ["Rang Mahal Red Fort"], "red_fort",
     "Rang Mahal is one of the marble palace pavilions on the Red Fort's Yamuna terrace, part of the imperial zenana sequence beyond the Diwan-i-Khas."),
    ("Hampi — Stone Chariot", "Hampi", ["Vittala chariot"], "hampi",
     "The stone chariot in Hampi's Vittala Temple courtyard is a shrine-form ratha of the Vijayanagara sacred centre, among the most visited sculptures on the Tungabhadra floodplain."),
    ("Ellora — Jain caves", "Aurangabad", ["Ellora Cave 32", "Indra Sabha"], "ellora",
     "Ellora's southern Jain group (including the Indra Sabha, Cave 32) continues the cliff sequence beyond the Hindu and Buddhist caves, illustrating three faiths in one basalt face."),
    ("Khajuraho — Lakshmana Temple", "Khajuraho", ["Lakshmana Khajuraho"], "khajuraho",
     "Lakshmana Temple in the western group is an earlier Chandela Nagara temple than Kandariya Mahadeva, still densely sculpted and on the same ASI ticketed lawn."),
    ("Sanchi — Stupa 2", "Sanchi", ["Sanchi Stupa 2"], "sanchi",
     "Sanchi Stupa 2, down the hill from the Great Stupa, preserves early Buddhist railing medallions and is a quieter official monument in the same UNESCO sanctuary."),
    ("Mahabalipuram — Krishna's Butter Ball", "Mahabalipuram", ["Butter Ball", "Krishna's Butterball"], "mahabalipuram",
     "Krishna's Butter Ball is a naturally perched granite boulder on the Mahabalipuram hill, a popular photo stop within the Pallava monument landscape, not a separate ticketed cave."),
    ("Konark — Natamandira platform", "Konark", ["Konark dance hall"], "konark",
     "The natamandira (dance hall) platform in front of Konark's jagamohana is part of the chariot-temple's east-facing ritual sequence, now an open sculpted plinth."),
    ("Qutb Minar — Quwwat-ul-Islam mosque", "Delhi", ["Quwwat ul Islam"], "qutb",
     "The Quwwat-ul-Islam mosque is the congregational prayer court at the foot of Qutb Minar, begun in the late 12th century around the Iron Pillar."),
    ("Humayun's Tomb — Isa Khan garden-tomb", "Delhi", ["Isa Khan Niyazi"], "humayun",
     "Isa Khan's tomb and mosque, just before Humayun's west gate, is an earlier Sur-period garden-tomb in the same precinct, a quieter octagonal mausoleum than the main double dome."),
    ("Fatehpur Sikri — Buland Darwaza climb", "Agra", ["Buland Darwaza steps"], "fatehpur",
     "The Buland Darwaza is approached by a steep flight of steps from the town side into Fatehpur Sikri's mosque court — the victory gate of Akbar's Friday mosque."),
    ("Golden Temple — Parikrama marble", "Amritsar", ["Darbar Sahib parikrama"], "sgpc",
     "The marble parikrama around the Amrit Sarovar is the circumambulation path of Harmandir Sahib; head covering and washing of feet are part of the gurdwara discipline."),
    ("Meenakshi — Thousand Pillar Hall", "Madurai", ["Aayiram Kaal Mandapam"], "tourism_india",
     "The Thousand Pillar Hall (Aayiram Kaal Mandapam) is a vast colonnaded mandapa in the Meenakshi complex, a living-temple museum space with dress rules, not a secular gallery."),
    ("Brihadisvara — inner prakara", "Thanjavur", ["Thanjavur courtyard"], "chola",
     "Brihadisvara's inner prakara and subsidiary shrines wrap the granite vimana; it is a living Chola temple with worship hours, part of UNESCO's Great Living Chola Temples."),
    ("Rani-ki-Vav — well shaft", "Patan", ["Rani ki Vav kund"], "rani_ki_vav",
     "The lowest levels of Rani-ki-Vav reach the well shaft, an inverted-temple descent through sculpted galleries that UNESCO lists at Patan."),
    ("Chittorgarh — Kirti Stambha", "Chittorgarh", ["Tower of Fame Chittor"], "hill_forts",
     "Kirti Stambha (Tower of Fame) is a Jain-carved tower inside Chittorgarh Fort, distinct from the taller Vijay Stambha on the same plateau citadel."),
    ("Jaisalmer — Jain temples in fort", "Jaisalmer", ["Jaisalmer Jain temples"], "hill_forts",
     "A cluster of richly carved Jain temples stands inside Jaisalmer Fort's living streets, part of the UNESCO hill-fort city rather than a separate desert shrine."),
]
