export type MonumentTicketMode = 'online' | 'official-info' | 'no-entry-ticket';

export type MonumentTicketLink = {
  id: string;
  city: string;
  aliases?: string[];
  monuments: string[];
  provider: string;
  url: string;
  mode: MonumentTicketMode;
  note: string;
};

/**
 * Official ticket channels for the major monuments already present in
 * Zentrip's knowledge corpus. URLs are intentionally provider-owned: prices,
 * availability, and checkout rules can change outside the app.
 */
export const MONUMENT_TICKET_LINKS: MonumentTicketLink[] = [
  {
    id: 'asi-agra',
    city: 'Agra',
    monuments: [
      'Taj Mahal',
      'Agra Fort',
      'Fatehpur Sikri',
      "Akbar's Tomb",
      "Itimad-ud-Daulah's Tomb",
      'Mehtab Bagh',
      'Ram Bagh',
      "Mariam's Tomb",
    ],
    provider: 'Archaeological Survey of India',
    url: 'https://asi.paygov.org.in/asi-webapp/#/ticketbooking',
    mode: 'online',
    note: 'Current ASI e-ticket portal for Agra monuments.',
  },
  {
    id: 'asi-delhi',
    city: 'Delhi',
    aliases: ['New Delhi'],
    monuments: [
      'Red Fort',
      'Qutb Minar',
      "Humayun's Tomb",
      'Purana Qila',
      'Safdarjung Tomb',
      'Tughlakabad Fort',
      'Feroz Shah Kotla',
      'Jantar Mantar, Delhi',
    ],
    provider: 'Archaeological Survey of India',
    url: 'https://asi.paygov.org.in/asi-webapp/#/ticketbooking',
    mode: 'online',
    note: 'Select Delhi Circle and the monument in the ASI portal.',
  },
  {
    id: 'rajasthan-state',
    city: 'Jaipur',
    aliases: ['Amer', 'Amber'],
    monuments: [
      'Amber Fort',
      'Hawa Mahal',
      'Jantar Mantar, Jaipur',
      'Albert Hall',
      'Sisodia Rani Garden',
      'Vidyadhar Garden',
      'Isarlat',
      'Nahargarh Fort',
    ],
    provider: 'Rajasthan Department of Archaeology & Museums',
    url: 'https://obms-tourist.rajasthan.gov.in/',
    mode: 'online',
    note: 'Rajasthan state online monument and museum ticket portal.',
  },
  {
    id: 'jaipur-city-palace',
    city: 'Jaipur',
    monuments: ['City Palace Museum, Jaipur'],
    provider: 'City Palace Museum Jaipur',
    url: 'https://citypalace.org/visit',
    mode: 'official-info',
    note: 'Official ticket and visitor information; the page currently directs visitors to palace gates for tickets.',
  },
  {
    id: 'udaipur-state',
    city: 'Udaipur',
    monuments: ['Government Museum Udaipur', 'Ahar Museum'],
    provider: 'Rajasthan Department of Archaeology & Museums',
    url: 'https://obms-tourist.rajasthan.gov.in/',
    mode: 'online',
    note: 'Rajasthan composite-ticket and museum portal.',
  },
  {
    id: 'udaipur-city-palace',
    city: 'Udaipur',
    monuments: ['City Palace Museum, Udaipur'],
    provider: 'City Palace Museum Udaipur',
    url: 'https://eticket.citypalacemuseum.org/',
    mode: 'online',
    note: 'Official Udaipur City Palace e-ticket portal.',
  },
  {
    id: 'jodhpur-mehrangarh',
    city: 'Jodhpur',
    monuments: ['Mehrangarh Fort', 'Jaswant Thada', 'Rao Jodha Desert Rock Park'],
    provider: 'Mehrangarh Museum Trust',
    url: 'https://mehrangarh.getepay.in/',
    mode: 'online',
    note: 'Official trust booking channel for fort and associated trails.',
  },
  {
    id: 'jaisalmer-trust',
    city: 'Jaisalmer',
    monuments: ['Jaisalmer Fort Palace Museum', 'Bada Bagh'],
    provider: 'Jaisalmer Trust',
    url: 'https://www.jaisalmertrust.com/',
    mode: 'official-info',
    note: 'Official trust portal; ticket booking is also offered through its official app.',
  },
  {
    id: 'rajasthan-composite-west',
    city: 'Bundi',
    aliases: ['Jhalawar'],
    monuments: ['Rani Ji Ki Baori', 'Sukh Mahal', 'Chaurasi Khambo Ki Chhatri', 'Gagron Fort'],
    provider: 'Rajasthan Department of Archaeology & Museums',
    url: 'https://obms-tourist.rajasthan.gov.in/',
    mode: 'online',
    note: 'State portal; availability depends on the selected monument and date.',
  },
  {
    id: 'rajasthan-hill-forts',
    city: 'Chittorgarh',
    aliases: ['Chittor'],
    monuments: ['Chittorgarh Fort'],
    provider: 'Rajasthan Department of Archaeology & Museums',
    url: 'https://obms-tourist.rajasthan.gov.in/',
    mode: 'online',
    note: 'Use the Rajasthan state portal to check the current fort ticket and timings.',
  },
  {
    id: 'rajasthan-kumbhalgarh',
    city: 'Kumbhalgarh',
    monuments: ['Kumbhalgarh Fort'],
    provider: 'Rajasthan Department of Archaeology & Museums',
    url: 'https://obms-tourist.rajasthan.gov.in/',
    mode: 'online',
    note: 'Use the Rajasthan state portal to check the current fort ticket and timings.',
  },
  {
    id: 'asi-mumbai',
    city: 'Mumbai',
    monuments: ['Elephanta Caves'],
    provider: 'Archaeological Survey of India',
    url: 'https://asi.paygov.org.in/asi-webapp/#/ticketbooking',
    mode: 'online',
    note: 'ASI entry ticket; ferry transport is separate.',
  },
  {
    id: 'asi-aurangabad',
    city: 'Aurangabad',
    aliases: ['Chhatrapati Sambhajinagar'],
    monuments: ['Ajanta Caves', 'Ellora Caves', 'Bibi-ka-Maqbara'],
    provider: 'Archaeological Survey of India',
    url: 'https://asi.paygov.org.in/asi-webapp/#/ticketbooking',
    mode: 'online',
    note: 'Select the Maharashtra Circle monument in the ASI portal.',
  },
  {
    id: 'asi-hampi',
    city: 'Hampi',
    monuments: ['Group of Monuments at Hampi', 'Vijaya Vittala Temple'],
    provider: 'Archaeological Survey of India',
    url: 'https://asi.paygov.org.in/asi-webapp/#/ticketbooking',
    mode: 'online',
    note: 'ASI ticketing applies to the ticketed monument enclosures.',
  },
  {
    id: 'asi-khajuraho',
    city: 'Khajuraho',
    monuments: ['Khajuraho Group of Monuments'],
    provider: 'Archaeological Survey of India',
    url: 'https://asi.paygov.org.in/asi-webapp/#/ticketbooking',
    mode: 'online',
    note: 'Select the Khajuraho monument group in the ASI portal.',
  },
  {
    id: 'asi-sanchi',
    city: 'Sanchi',
    monuments: ['Buddhist Monuments at Sanchi'],
    provider: 'Archaeological Survey of India',
    url: 'https://asi.paygov.org.in/asi-webapp/#/ticketbooking',
    mode: 'online',
    note: 'ASI ticketing for the Sanchi monument complex.',
  },
  {
    id: 'asi-bodh-gaya',
    city: 'Bodh Gaya',
    aliases: ['Bodhgaya'],
    monuments: ['Mahabodhi Temple Complex'],
    provider: 'Archaeological Survey of India',
    url: 'https://asi.paygov.org.in/asi-webapp/#/ticketbooking',
    mode: 'official-info',
    note: 'The temple is a living pilgrimage site; verify entry, worship, and photography rules locally.',
  },
  {
    id: 'asi-pattadakal',
    city: 'Pattadakal',
    monuments: ['Group of Monuments at Pattadakal', 'Virupaksha Temple, Pattadakal'],
    provider: 'Archaeological Survey of India',
    url: 'https://asi.paygov.org.in/asi-webapp/#/ticketbooking',
    mode: 'online',
    note: 'Select Pattadakal in the ASI ticket portal.',
  },
  {
    id: 'asi-konark',
    city: 'Konark',
    aliases: ['Puri'],
    monuments: ['Sun Temple, Konark'],
    provider: 'Archaeological Survey of India',
    url: 'https://asi.paygov.org.in/asi-webapp/#/ticketbooking',
    mode: 'online',
    note: 'ASI entry ticket; Odisha light-and-sound tickets use the separate OTDC portal.',
  },
  {
    id: 'odisha-konark-show',
    city: 'Konark',
    monuments: ['Konark Sun Temple Light & Sound Show'],
    provider: 'Odisha Tourism Development Corporation',
    url: 'https://www.bookodisha.com/',
    mode: 'online',
    note: 'Official OTDC booking channel for the light-and-sound experience.',
  },
  {
    id: 'asi-mahabalipuram',
    city: 'Mahabalipuram',
    aliases: ['Mamallapuram'],
    monuments: ['Shore Temple', 'Five Rathas', 'Group of Monuments at Mahabalipuram'],
    provider: 'Archaeological Survey of India',
    url: 'https://asi.paygov.org.in/asi-webapp/#/ticketbooking',
    mode: 'online',
    note: 'ASI ticketing for the Pallava monument group.',
  },
  {
    id: 'asi-thanjavur',
    city: 'Thanjavur',
    aliases: ['Tanjore'],
    monuments: ['Brihadisvara Temple', 'Great Living Chola Temples'],
    provider: 'Archaeological Survey of India',
    url: 'https://asi.paygov.org.in/asi-webapp/#/ticketbooking',
    mode: 'official-info',
    note: 'The temple is generally free to enter; verify current rules before visiting.',
  },
  {
    id: 'asi-old-goa',
    city: 'Old Goa',
    aliases: ['Goa', 'Velha Goa'],
    monuments: ['Basilica of Bom Jesus', 'Se Cathedral', 'Churches and Convents of Goa'],
    provider: 'Government of Goa / ASI',
    url: 'https://www.goa.gov.in/places/basilica-church-for-churches/',
    mode: 'official-info',
    note: 'Official visitor information; church entry is not a standard ASI e-ticket product.',
  },
  {
    id: 'asi-hyderabad',
    city: 'Hyderabad',
    monuments: ['Charminar', 'Golconda Fort', 'Qutb Shahi Tombs'],
    provider: 'Archaeological Survey of India',
    url: 'https://asi.paygov.org.in/asi-webapp/#/ticketbooking',
    mode: 'online',
    note: 'Use the ASI portal where the selected Hyderabad monument is listed.',
  },
  {
    id: 'asi-ahmedabad',
    city: 'Ahmedabad',
    aliases: ['Ahmadabad'],
    monuments: ['Historic City of Ahmadabad', 'Bhadra Fort'],
    provider: 'Archaeological Survey of India / Ahmedabad tourism',
    url: 'https://culture.gov.in/monuments',
    mode: 'official-info',
    note: 'Official monument information; entry and heritage-walk access varies by site.',
  },
  {
    id: 'chandigarh-capitol',
    city: 'Chandigarh',
    monuments: ['Capitol Complex', 'Open Hand Monument'],
    provider: 'Chandigarh Heritage Conservation Committee',
    url: 'https://chandigarh.gov.in/tourism',
    mode: 'official-info',
    note: 'Capitol Complex access is controlled; check the official visitor instructions before going.',
  },
  {
    id: 'mysuru-palace',
    city: 'Mysuru',
    aliases: ['Mysore'],
    monuments: ['Mysuru Palace'],
    provider: 'Mysuru Palace Board',
    url: 'https://mysorepalace.karnataka.gov.in/',
    mode: 'official-info',
    note: 'Official palace site; online ticket availability should be confirmed on the live page.',
  },
  {
    id: 'mysuru-chamundi',
    city: 'Mysuru',
    monuments: ['Chamundeshwari Temple'],
    provider: 'Government of Karnataka',
    url: 'https://e-ticket.chamundeshwaritemple.in/',
    mode: 'online',
    note: 'Official Karnataka temple ticket/seva portal.',
  },
  {
    id: 'victoria-memorial',
    city: 'Kolkata',
    monuments: ['Victoria Memorial Museum', 'Victoria Memorial Gardens'],
    provider: 'Victoria Memorial Hall',
    url: 'https://victoriamemorial-cal.org/visit-us/',
    mode: 'online',
    note: 'Official visit page with museum and garden ticket actions.',
  },
  {
    id: 'meenakshi-temple',
    city: 'Madurai',
    monuments: ['Meenakshi Amman Temple'],
    provider: 'Tamil Nadu Hindu Religious & Charitable Endowments',
    url: 'https://maduraimeenakshi.hrce.tn.gov.in/',
    mode: 'online',
    note: 'Official temple services/e-ticket portal; services vary by date and ceremony.',
  },
  {
    id: 'kashi-vishwanath',
    city: 'Varanasi',
    monuments: ['Kashi Vishwanath Temple'],
    provider: 'Shri Kashi Vishwanath Temple Trust',
    url: 'https://darshan.kashi.gov.in/',
    mode: 'online',
    note: 'Official Kashi Darshan portal for ticketed Sugam Darshan and services.',
  },
  {
    id: 'asi-sarnath',
    city: 'Varanasi',
    monuments: ['Sarnath', 'Dhamek Stupa'],
    provider: 'Archaeological Survey of India',
    url: 'https://asi.paygov.org.in/asi-webapp/#/ticketbooking',
    mode: 'online',
    note: 'ASI ticketing for the ticketed Sarnath monument/museum selection.',
  },
  {
    id: 'statue-of-unity',
    city: 'Kevadia',
    aliases: ['Ekta Nagar', 'Vadodara'],
    monuments: ['Statue of Unity', 'Viewing Gallery', 'Valley of Flowers', 'Jungle Safari'],
    provider: 'Statue of Unity Area Development Authority',
    url: 'https://booking.soutickets.in/',
    mode: 'online',
    note: 'Official ticket portal for entry passes and attractions.',
  },
  {
    id: 'rani-ki-vav',
    city: 'Patan',
    monuments: ['Rani-ki-Vav'],
    provider: 'Archaeological Survey of India',
    url: 'https://asi.paygov.org.in/asi-webapp/#/ticketbooking',
    mode: 'online',
    note: 'ASI ticketing for the Patan monument.',
  },
  {
    id: 'free-landmarks',
    city: 'India',
    monuments: ['India Gate', 'Gateway of India', 'Lotus Temple', 'Golden Temple'],
    provider: 'Monument/trust visitor information',
    url: 'https://www.incredibleindia.gov.in/en/monuments-booking',
    mode: 'no-entry-ticket',
    note: 'These landmarks generally do not use a standard paid monument-entry ticket; check event or special-access rules.',
  },
  {
    id: 'free-mumbai-landmarks',
    city: 'Mumbai',
    monuments: ['Gateway of India', 'Chhatrapati Shivaji Maharaj Terminus'],
    provider: 'Government tourism / heritage visitor information',
    url: 'https://www.incredibleindia.gov.in/en/monuments-booking',
    mode: 'no-entry-ticket',
    note: 'Public landmark access is generally free; museums, guided tours, and ferry rides may charge separately.',
  },
  {
    id: 'free-amritsar-landmarks',
    city: 'Amritsar',
    monuments: ['Golden Temple'],
    provider: 'SGPC visitor information',
    url: 'https://sgpc.net/',
    mode: 'no-entry-ticket',
    note: 'Darshan is generally free; follow the gurdwara’s current visitor, dress, and security rules.',
  },
];

function normalize(value: string): string {
  return value.trim().toLowerCase().replace(/[.'’]/g, '').replace(/\s+/g, ' ');
}

export function monumentTicketsForCity(city?: string): MonumentTicketLink[] {
  const wanted = normalize(city || '');
  if (!wanted) return MONUMENT_TICKET_LINKS;
  const matches = MONUMENT_TICKET_LINKS.filter((item) =>
    [item.city, ...(item.aliases ?? [])].some((value) => normalize(value) === wanted)
  );
  return matches.length ? matches : MONUMENT_TICKET_LINKS;
}
