"""trip memory notes and user preferences

Revision ID: eed6303d2ab9
Revises: 3b7f2c9d6e14
Create Date: 2026-08-26 05:14:44.865841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eed6303d2ab9'
down_revision: Union[str, None] = '3b7f2c9d6e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('statement', sa.String(length=500), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=False)
    op.create_table('trip_memory_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_memory_notes_trip_id'), 'trip_memory_notes', ['trip_id'], unique=False)
    # NOTE: autogenerate also proposed dropping ~13 indexes on unrelated pre-existing
    # tables (itinerary_days, knowledge_*, onboarding_calls, outcomes,
    # provider_observations, recommendations). Those exist in the live DB from earlier
    # migrations but aren't declared as index=True in models.py — a pre-existing
    # drift between migration history and the ORM, not something this migration should
    # touch. Deliberately stripped from both upgrade() and downgrade() below so this
    # migration only adds the two new memory tables.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_memory_notes_trip_id'), table_name='trip_memory_notes')
    op.drop_table('trip_memory_notes')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
